### PR TITLE
Fixed Orientation Issue

### LINKED ISSUE #1613: Bug in the landscape mode of an image.
**Actual Behaviour**

When you click on an image,it opens in portrait mode and when you rotate the image to landscape mode the first image of the current album is as shown in the below screenshot.Even after rotating back to portrait mode the images are not displayed properly.

**Expected Behaviour**

There should be no space above the image and the first image must be shown properly.

**Steps to reproduce it**

Open the image in portrait mode, and when you view it in landscape mode it should be displayed properly.

**Screenshots of the issue**

26655443_2002590003349428_1186741276_o

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by raj10071997**
Fix #1613

Changes: Fixed the orientation issue - both landscape and portrait in SingleMediaActivity.

### CODE REVIEW

**Comment by batbrain7** [comment]
@raj10071997 A PR has already been sent regarding this issue please close this PR and the issue you created was already present as #1144 
Please check existing issues and PRs before submitting a new one.   :)

**Comment by raj10071997** [comment]
@mohitmanuja  Please resolve this clash. I know that there is already a PR sent by @batbrain7. But I have also put my time in finding the solution for the issue. Please review this PR also.

**Comment by raj10071997** [comment]
@codedsun @mohitmanuja @anantprsd5  Please resolve the above clash and review this PR too. If it requires me to close the PR, I will close it.

**Comment by raj10071997** [comment]
Thanks @anantprsd5 . I will not repeat the same mistake next time and will collaborate with others. :smile:

**Pull request merged**
