### PR TITLE
fix: Local Photos Not Responding [ #72 ]

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Implemented a lazyload mechanism to handle large galleries

Fixes issue #[72]

Changes:
- Earlier the whole gallery was loaded when the app is starting
- That has a bad impact on huge galleries
- A lazyload implementation is used to load 21 images per once

### CODE REVIEW

**Comment by dynamitechetan** [comment]
on click of plus button its adding the same photos again in the grid.

**Comment by CloudyPadmal** [comment]
I checked with different loading amounts now
- 3
- 6
- 10
- 21

They load normally to me! Different images!

But when I take a picture, sometimes this error comes and crash! Does it happen to you?

screenshot from 2017-03-04 15-49-17

**Comment by CloudyPadmal** [comment]
@pa1pal @Abhi2424shek can you review this? :) This fix is needed to handle large galleries!

**Comment by CloudyPadmal** [comment]
@pa1pal that camera2 permission crash happens to me sometimes when I switch to camera and view gallery again! I'll catch the Null Pointer and send a PR soon! :+1:

**Comment by Abhi2424shek** [comment]
Can't you do it here pls

**Comment by CloudyPadmal** [comment]
@Abhi2424shek @pa1pal Done!!! :raised_hands:

**Comment by CloudyPadmal** [comment]
Thank you @pa1pal :blush: :medal_military:

**Pull request merged**
