### PR TITLE
Automatically apk update

### LINKED ISSUE #27: Automatically build an apk file in the apk branch
The goal of this issue is to get an apk on each merged pull request build in the apk branch.

Use travis to build apks automatically. You can check other FOSSASIA projects e.g. Open Event Android and Susi Android how it is done there.

### PR DESCRIPTION
**Pull request by Heredroky**
@mariobehling With this PR I fixed #27, you can check it. the apk that is and will be generated with every commit is "app-debug.apk", you can find it in the folder "sample-apk" in the branch "apk", if you want to check it, here it is a [Link](https://github.com/Heredroky/phimpme-android/blob/apk/sample-apk/app-debug.apk). You can see that it is automatically generated by checking the commits of the "apk" branch.

After the explanation above, now I am going to tell you how make it work in fossasia's repository, you have to follow this steps:

1. Merge this PR
2. Generate a Personal Access Token on Github and check the following options:
screen shot 2017-01-09 at 9 26 54 pm

3. Go to the [Travis phimpme-android page](https://travis-ci.org/fossasia/phimpme-android)
4. Go to settings
5. Go to Environment Variables and create one with the name GITHUB_API_KEY and the value will be the generated Personal Access Token that you created on step 2
6. Replace the line: 
`git clone --quiet --branch=apk  https://heredroky:$GITHUB_API_KEY@github.com/heredroky/phimpme-android  apk > /dev/null`
with:
`git clone --quiet --branch=apk  https://fossasia:$GITHUB_API_KEY@github.com/fossasia/phimpme-android  apk > /dev/null`
7. You are good to go 😄 

Here, you can see screenshots of the latest generated app working: 
screenshot_20170109-205527
screenshot_20170109-205539

### CODE REVIEW

**Comment by mariobehling** [comment]
@Heredroky The apk should be in another branch. Otherwise it messes up the commits. We had some issues with it in other projects. That is why it would be best to have it in another branch. Please check the Susi Android project. We follow this approach here.

**Comment by Heredroky** [comment]
When I wrote that I didn't know how to put it in the branch "apk", but now, the app is generated in the branch "apk", nevermind that message :D

**Comment by Heredroky** [comment]
@mariobehling What do you think?

**Comment by Heredroky** [comment]
@mariobehling The commits of the generated apk will be always in apk branch

**Comment by pa1pal** [comment]
@Heredroky I look it into your repo. The apk branch contains complete code. Why not only the apk files in the apk branch like in the [https://github.com/fossasia/susi_android](url). 
Look at this [PR](https://github.com/fossasia/susi_android/pull/99) on Susi.
Also see why checks failed?

**Comment by Heredroky** [comment]
@pa1pal  It failed, because I started the script with a comment, and that comment is important

**Comment by Heredroky** [comment]
@pa1pal  I think that it is better to do that later, step by step

**Comment by pa1pal** [comment]
@Heredroky Good effort. But failed checks cannot be merged. Fix this. Also branch works fine but remove the old sample-apk folder and only add apk files in apk branch.

**Comment by Heredroky** [comment]
@pa1pal I fixed the fails

**Comment by Heredroky** [comment]
@pa1pal Talking now, about the issue of the branch, in my opinion, it is better if someone from fossasia do it, because if I do it, and then I make a PR, it would contain all the commits from my branch apk from my repo, and it would be a mess. Cheers! 😄

**Comment by Heredroky** [comment]
@pa1pal @mariobehling Can this be merged?

**Comment by Heredroky** [comment]
@mariobehling What do you think?

**Comment by mariobehling** [comment]
@Heredroky Thanks. Please follow @pa1pal's guidance.

@pa1pal Please merge if you think it is the right direction. We can also iterate and make further improvements in next steps.

**Comment by pa1pal** [comment]
@Heredroky You are in right direction so I'm merging it now. Will improve in further steps.

**Pull request merged**
