### PR TITLE
fix#2223: Twitter link made working

### LINKED ISSUE #2223: Twitter Link not working
**Actual Behaviour**

On clicking the twitter icon on about section, it says user not found

**Expected Behaviour**

The twitter media icon should redirect to the account of phimpme on twitter.

**Steps to reproduce it**

Go to About Us

**LogCat for the issue**

None

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2223 : Twitter link working

Changes: 
Modified the intent parameters

Screenshots of the change: 
Opens the account of Phimp.me on twitter

### CODE REVIEW

**Comment by codedsun** [comment]
@sauravvishal8797 Please check it!

**Comment by codedsun** [comment]
@abishekvashok Shall this be added to .gitignore?

**Comment by abishekvashok** [comment]
>  Shall this be added to .gitignore?

Best would be not to, many Linux desktop environments also have similar files with different extension, `.dolfin` in kde is an example. It would be better if you could remove it.

**Comment by codedsun** [comment]
@abishekvashok Great, just doing it!

**Comment by codedsun** [comment]
@abishekvashok removed, but I think these .DSStore files are on the main repo. Please check

**Comment by abishekvashok** [comment]
Yeah. You removed those as well :) cheers

**Pull request merged**
