### PR TITLE
chore: Added spotless plugin and refactored code.

### LINKED ISSUE #2741: Migration to androidX
@sauravvishal8797 Can I work on this?

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2741

Changes: Added spotless plugin to maintain proper code formatting for java.
 
Files changed: travis.yml, build.gradle(app)

Rest of the files just have been refactored by `./gradlew spotlessApply`
It refactors each file which contains, extra newlines, extra parentheses, wrong indentations, and imports type errors and adds it to Travis so that in future these types of error can be detected automatically.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @mariobehling please review.

**Comment by iamareebjamal** [comment]
@yashk2000 Please work on automatic release process now, on priority

**Comment by yashk2000** [comment]
@iamareebjamal ok. Could you please tell me how to test the script once it is done?

**Comment by iamareebjamal** [comment]
I'll review it

**Pull request merged**
