### PR TITLE
Fixed #2221: Close search bar on back pressed

### LINKED ISSUE #2221: Search bar is remain open on back pressed
**Actual Behaviour**

The search bar remains open even if the back button is pressed and the app asks for exit the application.

**Expected Behaviour**

Search bar should close if open when the back button is pressed.

**Steps to reproduce it**

In the override method of `onBackPressed()` close the search bar if open.

**Would you like to work on the issue?**

Yes :+1:

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixed #2221

Changes: LFMainActivity.java

### CODE REVIEW

**Comment by liveHarshit** [comment]
@abishekvashok Yes, If the search view in open and back button is pressed, it will close the search box instead of exiting the application.

**Comment by abishekvashok** [comment]
> What if you are editing, and opened search by mistake, on back press would finish the edit mode now.

Please read it completely. I was asking about edit mode

**Comment by liveHarshit** [comment]
@abishekvashok Sorry, I can't get it. Which edit mode you are talking about. If I open search bar and go to edit mode and make some changes, on back pressed still show a dialog alert for discard changes. Please make it clear so I can fix it.

**Comment by abishekvashok** [comment]
> @liveHarshit basically what i think @abishekvashok is trying to say is that the elseif() statements get executed only when the if ones do not. But what is required is that Search bar operations do not depend on editmode.

Exactly

**Comment by abishekvashok** [comment]
Any updates?

**Comment by liveHarshit** [comment]
Someone please review

**Comment by liveHarshit** [comment]
@abishekvashok Should I make it fully independent from editMode. Check at the start on `onBackPressed()` and close it.

**Comment by abishekvashok** [comment]
The priority should be one which was choosen.

**Comment by liveHarshit** [comment]
Updated

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
