### PR TITLE
chore: Update build gradle version to 3.4.1 and updated to OpenCV4.0.1

### LINKED ISSUE #2744: App contains only 32 bit native binaries.
**Describe the chore**
The app currently contains only 32-bit native binaries. These will be banned after August. They should be replaced with 64-bit binaries.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2744 

Changes: Updated build gradle version beeing and openCV version to 4.0.1 to include 64-bit native libraries.

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok @sauravvishal8797 please review.

**Comment by iamareebjamal** [comment]
LGTM, but why 4.0.1

Since this is a big PR, why not upgrade to latest 4.1.0 instead of creating another big PR for this

Secondly, can't the files in `include` directory omitted and copied from the opencv sdk?

I suppose you have copied them from it, right? Why keep code in the repo that we don't maintain and have to update on each library update?

**Comment by yashk2000** [comment]
@iamareebjamal yes, we can omit the `include` directory.

I tried with 4.1.0 after 4.0.1 earlier, but it gave me some errors which were not faced with 4.0.1. So I sent the pr with 4.0.1. I'll try 4.1.0 once again.

**Comment by yashk2000** [comment]
And also omit the `include` directory.

**Comment by yashk2000** [comment]
@iamareebjamal omitting the `include` directory will be done by adding `/app/src/main/jni/include/` to the .gitignore file right?

**Comment by iamareebjamal** [comment]
Your PR should have about 10 files changed once you have omitted the include directory.

**Comment by yashk2000** [comment]
@iamareebjamal yes sir. I added `/app/src/main/jni/include/` to the `.gitignore` file, but the folder is still here.

**Comment by iamareebjamal** [comment]
It obviously will be. You have to delete it. Also, don't squash and force push because if it doesn't work, you won't be able to revert

**Comment by iamareebjamal** [comment]
Also, don't delete the folder in this PR, just revert the changes

**Comment by yashk2000** [comment]
> It obviously will be. You have to delete it. Also, don't squash and force push because if it doesn't work, you won't be able to revert

@iamareebjamal sir but `/app/src/main/3rdparty/` and `/app/src/main/jniLibs` are also in the `.gitignore`. I do not have to delete these folders before pushing changes.

**Comment by iamareebjamal** [comment]
Because they were never added in git

Once tracked, always tracked, doesn't matter if you add them in .gitignore after. Read about git tracked files and gitignore

**Comment by yashk2000** [comment]
Ohk sir. I'll delete the folder and push the changes. Thanks :)

**Comment by iamareebjamal** [comment]
> Also, don't delete the folder in this PR, just revert the changes

**Comment by iamareebjamal** [comment]
Don't delete. The point is to not have 630 changes in this PR. It should only have changes in makefiles and download scripts

**Comment by yashk2000** [comment]
@iamareebjamal  Sir but without deleting how will we make ignore the `include` file while pushing?
Should that be done in another pr?
Which changes do I revert back to then? Just updating the build gradle version?

**Comment by iamareebjamal** [comment]
> Sir but without deleting how will we make ignore the include file while pushing?
Should that be done in another pr?

Yes

> Which changes do I revert back to then?

All changes should be there except any change in include folder. The opencv script must be updated to copy required files to the include folder

**Comment by yashk2000** [comment]
> The opencv script must be updated to copy required files to the include folder

If I do this, then this error will happen:
`mv: cannot move ‘/home/travis/openCV/opencv/sdk/native/jni/include/opencv2’ to ‘app/src/main/jni/include/opencv2’: Directory not empty
`
For now, until the `include` folder is deleted, should I modify the script to first delete the existing contents of the folder and then move in the new folders?

**Comment by iamareebjamal** [comment]
Still 400+ changes. Same can be done with ` openCVLibrary401/` folder. Please don't add anything we are copying from the opencv SDK

In future, we'll use open cv aar like https://github.com/piruin/opencv-android

So that we don't need this utterly useless step and redundant code in the repo and can manage the dependency in sane way like other "normal" android libraries

```
implementation 'org.opencv:opencv-android:3.4.1'
```

Not doing it currently because the latest version is 3.4.1

**Comment by yashk2000** [comment]
@iamareebjamal openCVLibrary401 is not copied and pasted. It has to imported as a separate module. I think we should leave this because some changes have to made in the manifests and gradle files of both app and openCV module. This might not be very friendly for first-time contributors.

**Comment by yashk2000** [comment]
> In future, we'll use open cv aar like https://github.com/piruin/opencv-android

Yes sir, this is a very good idea.

**Comment by yashk2000** [comment]
@iamareebjamal is it alright now?

**Comment by yashk2000** [comment]
@iamareebjamal sir, is this alright now?

**Comment by yashk2000** [comment]
@iamareebjamal sir, is it ok now?

**Comment by iamareebjamal** [comment]
> openCVLibrary401 is not copied and pasted. It has to imported as a separate module. I think we should leave this

OK, but rename this to `openCV`, so that we don't have to change this every version. I have no idea why it was thought of as a good idea to add version code in module

**Comment by yashk2000** [comment]
Ok sir, on it.

**Comment by yashk2000** [comment]
> OK, but rename this to `openCV`, so that we don't have to change this every version. I have no idea why it was thought of as a good idea to add version code in module

@iamareebjamal done.

**Pull request merged**
