### PR TITLE
Geolocation Button opens Alert dialog Box if GPS is disabled

### PR DESCRIPTION
**Pull request by Subhankar29**
First steps for issue #89 

Changes: Added Alert dialog box. When Geolocation Button is clicked if GPS is disabled an alert dialog box pops to enable it. 
Geolocation Button does not do anything
screenshot_2017-03-17-23-47-15-866

Added material design.

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
@Subhankar29 the destination branch has to be `fossasia:development` :)

**Comment by Abhi2424shek** [comment]
Yes pls update it to development and I see your code is old. Pls do the needy.

**Comment by Subhankar29** [comment]
Ok. I will do it.

**Comment by Abhi2424shek** [comment]
Still it's to the master branch make it to the development branch.

**Comment by Subhankar29** [comment]
I have made the instructed changes, please review it.

**Comment by Abhi2424shek** [comment]
Pls resolve the conflicts.

**Comment by Abhi2424shek** [comment]
It's solved in his own another PR.

**Comment by Abhi2424shek** [comment]
#207

**Pull request closed without merging**
