### PR TITLE
chore: Fix travis build

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by adityastic** [comment]
just add  
`dist : trusty`

**Comment by iamareebjamal** [comment]
@adityastic Workaround

**Comment by adityastic** [comment]
@iamareebjamal until Travis fixes their cache issue

**Comment by yashk2000** [comment]
@iamareebjamal until the Travis issue is fixed, should we go for #2780?

**Comment by abishekvashok** [comment]
Restart the tests pls

**Pull request closed without merging**
