### PR TITLE
Imporved design

### PR DESCRIPTION
**Pull request by Abhi2424shek**
Improved design of the app.
Done as part of GCI task: https://codein.withgoogle.com/dashboard/task-instances/5305516907560960/

**Describing the changed layouts one by one**
1.
After:
image
[There was some button overflows which looked bad]

2.
Before:
image

After:
image

3.
Before: 
image

After: 
image

4.
Before: 
image

After: 
image

_This change has affected many layouts (i.e, I changed the same before layouts to after) The progressbar also spins acting as a spinner via the files added to the `drawable/` folder _
5. 
Before:
image

After:
image

6.
Before:
image

After:
image

I did not bother to change the core theme as I don't want to do this without a discussion. So I opened issue #30. After that we could modify the core design to complete material one. (Here I am implementing some partial tweaks to materialize only a small part of the app.)

### CODE REVIEW

**Comment by pa1pal** [comment]
@Abhi2424shek Good effort. 
Any other modification which you can do?

**Comment by Abhi2424shek** [comment]
@pa1pal i would give a PR to resolve #30 soon...

**Comment by Abhi2424shek** [comment]
But now can you merge this?

**Comment by pa1pal** [comment]
sure @Abhi2424shek .

**Pull request merged**
