### PR TITLE
UI Change for Edit Image

### PR DESCRIPTION
**Pull request by dynamitechetan**
Changes: 
1. Improved Performance of Edit Image Activity
2. Better UI

Screenshots for the change: 

<table>
<th>PREVIOUS</th><th>NOW</th>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
Unify the background colours. Remember we are following light theme.

**Comment by dynamitechetan** [comment]
@Abhi2424shek please review.

**Comment by Abhi2424shek** [comment]
Ok sorry for not mentioning om the first comment. I am sorry. Can you also convert the textboxes to material design?@dynamitechetan

**Comment by dynamitechetan** [comment]
@pa1pal vector drawables work only on Android 5.0 above.

**Comment by pa1pal** [comment]
@dynamitechetan There is  backwards compatibility. The Gradle plugin will automatically generate raster PNG images for API level 20 and below during build time.

**Comment by dynamitechetan** [comment]
@pa1pal removed pngs and used vector images
@Abhi2424shek removed border for edit text (See updated Screenshot)

**Pull request merged**
