### PR TITLE
fix: Added alert if user clicks tick button in stickers section without adding any stickers.

### LINKED ISSUE #2656: Apply stickers tick button enable even if no stickers are added
**Describe the bug**

Apply stickers tick button enable even if no stickers are added

**To Reproduce**
1. Go to stickers option in edit image

**Expected behavior**
tick should be only enable if any stickers are added to image

**Screenshots**
screenshot_20190227-012955

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Moto G5s Plus |
|Android Version| Oreo 8.1   |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2656 

Changes: If user presses tick button in stickers section without using any sticker, an alert is shown. 
I have not used `button.setEnabled(false);` because it will make the user confused as to why the tick button is not working.

Screenshots of the change: 

screencap

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @abishekvashok @mariobehling please review.

**Comment by yashk2000** [comment]
@abishekvashok @mariobehling which is better:

screencap

screencap

**Comment by abishekvashok** [comment]
2nd one!

**Comment by yashk2000** [comment]
@abishekvashok sure :+1:

**Comment by yashk2000** [comment]
@abishekvashok please review. I have updated the icon.

**Comment by yashk2000** [comment]
@abishekvashok could you please squash it here :sweat_smile:? If I squash, it might lead to a few unexpected changes over here which I'll have to revert again.

**Pull request merged**
