### PR TITLE
Fix #1894-App crash fixed for deleting favourite marked images from a…

### LINKED ISSUE #1894: App crashes when deleting an image which is in favourites from AllphotosMode.
**Actual Behaviour**

The app crashes when you try delete the image which is in favourites from any album or AllphotosMode.

**Expected Behaviour**

The app shouldn't crash.

**Would you like to work on the issue?**
 
Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
…lbums or all photos mode.

Fixed #1894 
Changes: The issue was in removing the path of the deleted image from the favorites table in the realm database, so added a new ArrayList to keep track of the images deleted from the phone storage while traversing through the image paths present in the favorites table and then removing the paths from the favorites table by traversing through the ArrayList(keeping track of all the fav marked photos that have been deleted permanently from the storage).

### CODE REVIEW

**Comment by mariobehling** [comment]
Please check that Travis passes.

**Comment by sauravvishal8797** [comment]
@mariobehling Yes sure, working on fixing the Travis build.

**Comment by sauravvishal8797** [comment]
@mariobehling @anantprsd5 Travis check is fixed, please review and merge this commit.

**Comment by anantprsd5** [comment]
Please resolve conflicts

**Pull request merged**
