### PR TITLE
Fix#1237 App doesn't crash on selecting filter

### LINKED ISSUE #1237: App Crashing after selecting Threshold Filter
**Actual Behaviour**
Currently when the user selects Manglow filter or any other filter and then without applying it ,select the Threshold filter the app crashes.

**Expected Behaviour**
The app shouldn't crash.

**Steps to reproduce it**
1) Select any image
2) Go to the edit image mode
3) Select any filter other than threshold.
4) Now without applying it select Threshold filter.

**Screenshots of the issue**
appcrash 1

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by sridharjajoo**
Fix #1237 

Changes: 
Earlier the app was crashing after we selected a certain filter and then without applying it selected another filter by scrolling the horizontal recycler view to the right.This problem had arised because of the use of findViewHolderForAdapterPosition() returned null as the colour Transparent was being applied on a viewholder which wasn't present on the screen after scrolling.

### CODE REVIEW

**Comment by sridharjajoo** [comment]
@anantprsd5 @mohitmanuja kindly review the pr.

**Comment by anantprsd5** [comment]
@sridharjajoo fix the codacy issues.

**Comment by sridharjajoo** [comment]
To fix the issue should I make another commit in this PR or try to squash the commits?
@anantprsd5

**Comment by mohitmanuja** [comment]
Try to squash the commits.

**Comment by sridharjajoo** [comment]
@anantprsd5 @mohitmanuja Is it ok?Kindly review.

**Pull request merged**
