### PR TITLE
fixed single media activity snackbar position

### LINKED ISSUE #2644: wrong position of snackbar in single media activity.
**Describe the bug**

while using any of the functions like renaming, moving etc the snackbar displayed are positioned incorrectly.
**To Reproduce**

1. Go to 'any album'
2. Click on ' an image'
3. open the overflow menu.
4. perform any action. the snackbar displayed are positioned incorrectly.

**Expected behavior**

the snackbar displayed should lie just above the navigation bar.

**Screenshots**

whatsapp image 2019-02-25 at 01 00 31
whatsapp image 2019-02-25 at 01 00 32

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2644 

Changes: 
snackbar position changed. now it lies just above bottom bar.

Screenshots of the change: 
whatsapp image 2019-03-05 at 18 26 20

### CODE REVIEW

**Comment by yashk2000** [comment]
@kk63852 are you sure this works? This was how it was earlier and the bottom bar and snackbars were overlapping.

**Comment by kk63852** [comment]
Works fine on my device. If it is not working on your device then i'll have a few more checks.

**Comment by yashk2000** [comment]
Ok. Maybe it's an issue with just my device. Please inform me if it works fine on other devices.

**Comment by kk63852** [comment]
Will surely do.

**Comment by abishekvashok** [comment]
Updates

**Comment by kk63852** [comment]
Its not fixed yet. I'll soon send another commit once my internals are over.

**Comment by mariobehling** [comment]
@kk63852 Thanks for working on this. As I am not sure, you are able to join back in I am closing this PR for now due to inactivity. Please open a new PR with further changes if any. Thank you.

**Pull request closed without merging**
