### PR TITLE
feat: Apply spotless plugin and refactor the code

### LINKED ISSUE #2421: Add spotless check to improve code quality
**Actual Behaviour**

Add spotless check according to java style guideline for improve code quality and optimize imports.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixed #2421 

Apply spotless according to java style guideline, refactor code and optimize imports.

### CODE REVIEW

**Comment by liveHarshit** [comment]
No new code is added. Its refactor with code style only. :+1:

**Comment by mariobehling** [comment]
This PR changes a whopping 215 files. Please describe what steps reviewers should take to review the changes in a timely manner and how you created the changes. It is apparently not possible to review these changes in a normal manual review in an acceptable time.

**Comment by abishekvashok** [comment]
Please don't change the intendation in this fashion!

**Comment by liveHarshit** [comment]
> Please don't change the intendation in this fashion!

I'm sorry, but The code is refactored automatically according to code style guideline.

**Comment by abishekvashok** [comment]
I guess since there are no changes other than intendation, this can be safely closed. If this is merged, conflicts would be created for forks. You can change the intendation of your system to match that of the repository and enjoy :)

**Comment by liveHarshit** [comment]
@abishekvashok What about PR #2743

**Pull request closed without merging**
