### PR TITLE
Fixes issue #421 App crashes when camera button on bottomnavigationbar is pressed 

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #421 
Changes: 
Used local parameters variable for setting parameters for changing picturesize for camera when item in resSpinner is selected.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @vinaysajjanapu we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/vinaysajjanapu/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vinaysajjanapu** [comment]
Can you share your logs

**Comment by mohitmanuja** [comment]
@vinaysajjanapu 
05-10 15:21:41.756 20153-20153/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: vn.mbm.phimp.me, PID: 20153
                                                   java.lang.RuntimeException: setParameters failed
                                                       at android.hardware.Camera.native_setParameters(Native Method)
                                                       at android.hardware.Camera.setParameters(Camera.java:1972)
                                                       at vn.mbm.phimp.me.Preview.surfaceChanged(**Camera2.java:1386**)
                                                       at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
                                                       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
                                                       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2082)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by vinaysajjanapu** [comment]
This is not the one which I faced and I am not facing it either

**Comment by mohitmanuja** [comment]
@vinaysajjanapu in that case, I will raise a new issue. I think it is happening on my device. 
Preview size is : 1080x1140

**Comment by vinaysajjanapu** [comment]
Or if you let me know the changes I can make in thia PR itself

**Comment by mohitmanuja** [comment]
@vinaysajjanapu I think in **surfaceChanged** method my preview size is 1080x1140 but as we are passing 0th index of getPicturesSize list and that is around 3000x4440 something. The solution is to request the closest available preview size to the one.

**Comment by vinaysajjanapu** [comment]
@mohitmanuja does that change worked? because I can't check as it is not happening on my device.

**Pull request closed without merging**
