### PR TITLE
fix: crash on connect to us on facebook in about section

### LINKED ISSUE #2868: Connect to us on facebook crashes
**Describe the bug**
On clicking connect to us on facebook, the app crashes

**To Reproduce**

1. Go to 'About'
2. Click on 'Connect to facebook' at the bottom
3. crash

**Expected behavior**

Should not crash

**Logs**
```
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=fb://facewebmodal/f?href=https://www.facebook.com/phimpmeapp }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.Activity.startActivityForResult(Activity.java:4762)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:4691)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:5081)
        at android.app.Activity.startActivity(Activity.java:5049)
        at org.fossasia.phimpme.gallery.activities.AboutActivity$10.onClick(AboutActivity.java:229)
        at android.view.View.performClick(View.java:6710)
        at android.view.View.performClickInternal(View.java:6668)
        at android.view.View.access$3400(View.java:797)
        at android.view.View$PerformClick.run(View.java:26448)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7179)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2868 crash on connect to us on facebook in about section
Changes: Handled the activity not found exception and opened the app in chrome custom tab

Screenshots of the change:

### CODE REVIEW

**Comment by yashk2000** [comment]
@codedsun I wasn't able to reproduce this issue on my device.

**Comment by codedsun** [comment]
@yashk2000 , @prudhvir3ddy logout of  fb then test.

**Comment by abishekvashok** [comment]
I guess this happens when one has older fb app versions or when the fb app is not installed @yashk2000

**Comment by abishekvashok** [comment]
Hey @codedsun pls update your branch to reflect the latest changes in development:
`git pull upstream development --rebase`
where, `upstream` is a remote that points here.

**Comment by codedsun** [comment]
@abishekvashok Done, go ahead!

**Pull request merged**
