### PR TITLE
Fixed crash due to ripple effect below API<21 devices 

### PR DESCRIPTION
**Pull request by mohitmanuja**
Fixes issue #508 

Changes: 
Added ripple effect for API > 21 and API <21.

To check this issue run the app in **API <21 devices** .

### CODE REVIEW

**Comment by pa1pal** [comment]
same case with me. I will test this tomorrow on emulator.

**Comment by mohitmanuja** [comment]
@the-dagger I tried in Amazon Fire HDX Android 4.4.3 API 19 actually it is happening due to ripple effect which we are using in cardview. The way we are using ripple effect is supported above the API 21 devices so I just added that in drawable-v21 folder. And for below API 21, I added ripple effect in a drawable folder using the selector. 
Now the app will not crash in below API <21.

**Comment by mohitmanuja** [comment]
@pa1pal @vinaysajjanapu @anantprsd5 @Subhankar29 Please review it. Try to run app below API <21 devices.

**Comment by mohitmanuja** [comment]
@pa1pal @vinaysajjanapu Yes, I am also facing same error will look into it.

**Comment by pa1pal** [comment]
@vinaysajjanapu @mohitmanuja Please check now.

**Comment by mohitmanuja** [comment]
@pa1pal Working now.

**Pull request merged**
