### PR TITLE
Created new website for the app

### LINKED ISSUE #2253: Update website design (GCI Task)
**Actual Behaviour**

The phimp.me Android project has a basic website using the Mark-down files. 

**Expected Behaviour**

New Website with Material Design (Lading Page)
QR Codes

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
Fixed #2253

Changes: Full gh-pages branch changed

http://niteshkumarniranjan.github.io/phimpme-android

Screenshots of the change: 
screenshot from 2018-10-27 23-04-01

screenshot from 2018-10-27 23-04-26

### CODE REVIEW

**Comment by abishekvashok** [comment]
Ping me when you are ready with this

**Comment by niteshkumarniranjan** [comment]
@abishekvashok I think it's ready it has all the components required.

**Comment by abishekvashok** [comment]
Please enable hosting in your repos settings

**Comment by niteshkumarniranjan** [comment]
It's already enabled check it here: https://niteshkumarniranjan.github.io/phimpme-android/

**Comment by abishekvashok** [comment]
The get it on fdroid does nothing but opens the same website in the same window. Instead I suggest doing nothing there, removing the link around the button or even the button completely till we get it hosted on fdroid 

However, I could merge this anytime as it looks cool enough and the fdroid button could go into the site as well.

**Comment by niteshkumarniranjan** [comment]
It's because I was unable to find the app on fdroid so I can't link it.

**Comment by abishekvashok** [comment]
> It's because I was unable to find the app on fdroid so I can't link it.

The apps not hosted on fdroid yet.

**Comment by niteshkumarniranjan** [comment]
What should I do now?

**Comment by abishekvashok** [comment]
> I suggest doing nothing there, removing the link around the button or even the button completely till we get it hosted on fdroid
However, I could merge this anytime as it looks cool enough and the fdroid button could go into the site as well.

**Comment by niteshkumarniranjan** [comment]
@abishekvashok So I'm leaving it as it is? We will link it when the app will be hosted on FDroid

**Comment by abishekvashok** [comment]
Okay then!

**Comment by mariobehling** [comment]
This PR was not done according to the task specifications in GCI, that requested to build a website using Jekyll. I will have to revert that.

**Comment by niteshkumarniranjan** [comment]
BTW does "using Jekyll" means to use markdown files?

**Comment by mariobehling** [comment]
Markdown is part of it. I recommend you get started here: https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/

**Comment by niteshkumarniranjan** [comment]
Okay! I got it. I will do all the changes.

**Comment by niteshkumarniranjan** [comment]
Can I use html for homepage?

**Comment by mariobehling** [comment]
Please follow up in the issue and on chat. There is a lot of documentation about Jekyll out there. Basically content is kept in Mark-down.

**Pull request merged**
