### PR TITLE
Fix #1440-Add a Square Fit editing option in the App

### PR DESCRIPTION
**Pull request by ashley8jain**
First steps for issues #1140 

Changes: 

- [x] ThreeItemFragment for three items in Transform UI
- [x] Square fit icon
- [ ] Square fit Function

Screenshots for the change: 
screenshot_20180208-234242

### CODE REVIEW

**Comment by abishekvashok** [comment]
Please resolve codacy issues and the rest of the work here itself if possible.

**Comment by abishekvashok** [comment]
Ping @ashley8jain

**Comment by ashley8jain** [comment]
@abishekvashok it is one of challenge filter. I will do it as soon as possible. If anyone want to solve this filter, welcome.

**Comment by abishekvashok** [comment]
So what should I do, should I merge it?

**Comment by ashley8jain** [comment]
@abishekvashok yes please merge this, other can continue to solve this after merging

**Comment by abishekvashok** [comment]
Please wait :)

**Comment by abishekvashok** [comment]
There's an unused import, can you please remove it.

**Comment by ashley8jain** [comment]
@abishekvashok Done

**Comment by abishekvashok** [comment]
Still can you check and rectify the failing checks please?

**Comment by yashLadha** [comment]
@ashley8jain Can you the ss of the updated work?

**Comment by ashley8jain** [comment]
@abishekvashok ok I am rectifying now.
@yashLadha ss means?

**Comment by yashLadha** [comment]
SS - Screen Shot

**Comment by ashley8jain** [comment]
@yashLadha i just add three button on lower row and icon. as shown in screenshot in above description. Function of square Image is not implmented.

**Comment by ashley8jain** [comment]
@abishekvashok kindly merge now

**Comment by ashley8jain** [comment]
I will continue the work during GSOC '18

**Comment by abishekvashok** [comment]
Yea I will merge this after the branch get's updated and the build finished.

**Comment by yashLadha** [comment]
Can you change the title of the PR. It doesn't match the changes.

**Comment by sauravvishal8797** [comment]
@ashley8jain Please update the branch.

**Comment by mariobehling** [comment]
After feedback from devs on the channel, I am closing this. If this is still relevant and you want to commit it again, please reopen this PR or a new one. Thanks.

**Pull request closed without merging**
