### PR TITLE
Fixes  #1821 on screen keyboard hides on opening an album while searching

### LINKED ISSUE #1821: on screen keyboard doesn't hide when opening an album while searching
**Actual Behaviour**

When you search for an album and open an album while searching the on screen keyboard doesn't hide.

**Expected Behaviour**

The keyboard should hide when opening an album.

**Gif of the issue**

keyboard

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by raj10071997**
Fixed #1821

Changes: As the focus changes, the keyboard hides from the screen.

Gif of the change:
keyboard

### CODE REVIEW

**Comment by raj10071997** [comment]
@abishekvashok @mayank8318 Conflicts have been resolved. Sorry for the delay.

**Comment by abishekvashok** [comment]
It's fine. I've updated the branch pls wait till Travis runs and finishes.

**Comment by mayank8318** [comment]
@raj10071997 Can you please add a GIF?

**Comment by raj10071997** [comment]
@mayank8318 I have added the gif.

**Pull request merged**
