### PR TITLE
Replace nav bar with one from Design Support lib

### PR DESCRIPTION
**Pull request by kaine119**
Coming from issue #22 and [this GCI2016 task](https://codein.withgoogle.com/dashboard/task-instances/5984010633216000/).

Changes made:
- TabHost completely replaced with BottomNavigationBar
- Gallery, Upload and Settings activities replaced with fragments that can
    be swapped out in the main fragment container
- color_primary and color_secondary added to colors.xml
- Design Support library upgraded to 25.0.1
- Added material icons for gallery, camera, map, upload and settings

### CODE REVIEW

**Comment by pa1pal** [comment]
@kaine119 :+1: 
I will review it. But first check why travis is failing. Look in to the travis log.

**Comment by pa1pal** [comment]
@kaine119 Good effort. 
Now one main feature of the app adding accounts is breaking in Upload category. [This](https://github.com/kaine119/phimpme-android/blob/master/app/src/main/java/vn/mbm/phimp/me/Upload.java#L1033) does not allow the dialog, so I don't think it will work this way so do following steps.

- On [touch listener](https://github.com/fossasia/phimpme-android/blob/master/app/src/main/java/vn/mbm/phimp/me/Upload.java#L292) of the btnAdd popup a dialog fragment.
- Show only two items Facebook and Wordpress in the dialog.
- On their clicks do this for [facebook](https://github.com/kaine119/phimpme-android/blob/master/app/src/main/java/vn/mbm/phimp/me/Upload.java#L363) and [wordpress](https://github.com/kaine119/phimpme-android/blob/master/app/src/main/java/vn/mbm/phimp/me/Upload.java#L457).

**Comment by kaine119** [comment]
I think the existing system used to invoke dialogs is [deprecated](https://developer.android.com/reference/android/app/Activity.html#showDialog%28int,%20android.os.Bundle%29).

I moved the "add account" dialog to the newer system of putting it in its own fragment; the same should also be done to the other dialogs.

**Comment by pa1pal** [comment]
@kaine119  Good effort :+1: .
Few contribution tips
- Always do your work in a separate branch other than master. It will help you as well as the reviewer.
- Also always do check that your contribution should not break previous working features. And make all possible fixes before opening PR.

Cheers :+1:

**Comment by pa1pal** [comment]
@kaine119 What is the source of the images of the gallery, upload, settings?

**Comment by kaine119** [comment]
@pa1pal I used [this plugin](https://plugins.jetbrains.com/plugin/7658), which sources from [here](https://github.com/google/material-design-icons) and [here](http://www.androidicons.com/)

plugin [source](https://github.com/winterDroid/android-drawable-importer-intellij-plugin)

**Comment by pa1pal** [comment]
@kaine119 okay.

**Pull request merged**
