### PR TITLE
Fix: #1102 App Crashes while loading images

### LINKED ISSUE #1102: App Crashes while loading images
**Actual Behaviour**

When there are no images in device and clicking on image button to load images app crashes as demonstrated in gif

**Expected Behaviour**

If there is no images app should say "No Image found" 

**Steps to reproduce it**
Delete all photos from your device and open the app then click on the image button present in the main activity at top right corner

**LogCat for the issue**
FATAL EXCEPTION: AsyncTask 200  
 Process: org.fossasia.phimpme, PID: 1714
 java.lang.RuntimeException: An error occurred while executing doInBackground()

**Screenshots of the issue**

GIF - https://i.imgur.com/iV53Gcm.mp4

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by wookupmaker**
Fix #1102 

Changes: Added some conditional code in StorageProvider.java

Screenshots for the change: GIF (https://i.imgur.com/GRXCLnm.mp4)

### CODE REVIEW

**Comment by wookupmaker** [comment]
@anantprsd5  please review

**Comment by anantprsd5** [comment]
@wookupmaker Can you please provide the complete log for the crash.

**Comment by Subhankar29** [comment]
@wookupmaker Please upload the GIF in the issue section.

**Comment by wookupmaker** [comment]
@Subhankar29 here is the link for GIF that shows the bug https://i.imgur.com/iV53Gcm.gif

**Comment by wookupmaker** [comment]
@anantprsd5 here is the link for complete log when the app crashes https://goo.gl/N55tyc

**Comment by wookupmaker** [comment]
@anantprsd5 can you please delete this pull request because I messed up with my forked repository to get the code back for the error log and get the HEAD out date kind of error. So, I have to delete the repository and fork it again, I'll send another PR with proper code correction.
P.S.:- This is my first in OpenSource contribution So, I get stuck with git sometimes, I apologies if I'm making this process for complex then it should be.

**Comment by anantprsd5** [comment]
@wookupmaker You can simply close this PR and make a new one.

**Comment by wookupmaker** [comment]
@anantprsd5 okay, thanks. Closing the PR

**Pull request closed without merging**
