### PR TITLE
fix: crash on orientation change while crop

### LINKED ISSUE #2318: App crashes on changing orientation while cropping
**Actual Behaviour**

while cropping a image, on changing the screen orientation and clicking on tick mark the app crashes.

**Expected Behaviour**

image should cropped irrespective of screen orientation change.

**Steps to reproduce it**

Select an image and go to the editing activity.
Select transform.
Navigate to crop.
Now rotate your phone to landscape mode.
Tap on the tick button.
App crashes(BUG).

**LogCat for the issue**

screenshot 1

**Screenshots of the issue**

whatsapp image 2018-12-19 at 00 43 09
whatsapp image 2018-12-19 at 00 43 31
whatsapp image 2018-12-19 at 00 43 52
whatsapp image 2018-12-19 at 00 43 59

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2318 

Changes: was getting empty text in on saved instance state, handled that

Screenshots of the change:

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal Check this

**Comment by iamareebjamal** [comment]
Get PR approved by peers first

**Comment by codedsun** [comment]
@yashk2000 Please check!

**Comment by codedsun** [comment]
@yashk2000 Please check

**Comment by codedsun** [comment]
ezgif com-video-to-gif

@yashk2000 Check

**Comment by codedsun** [comment]
@yashk2000 Inputs please

**Comment by codedsun** [comment]
@yashk2000 Doing it.

**Comment by yashk2000** [comment]
If you change the crop settings in one mode, rotate the device and change the settings again and try to save the picture it works?

**Comment by codedsun** [comment]
Please detail in the steps

**Comment by yashk2000** [comment]
1) Enter the crop mode.
2) Rotate the device.
3) Change the crop settings to anything other than 1:1. Change the default crop square that appears.
4) Rotate the device again.
5) Check if changes are retained and saved on clicking save.

**Comment by codedsun** [comment]
@yashk2000 They are retained but the editImageActivity has bugs which causes of loading of image and setting the fragments again. So the first time when the configuration change occurs, 
1. Activity is recreated  in the activity get data function is called which runs an aysnc task of loading the image, meanwhile the Crop fragment sets all the data in the fragment

Now after the result of the loadImage(get Data function), the fragments are created again. Hence the changes are lost

**Comment by yashk2000** [comment]
Ok. You can open a new issue for the other problem. That can be fixed in a separate pr.

**Pull request merged**
