### PR TITLE
fix: removed stetho dependency

### LINKED ISSUE #2910: Remove stetho from app
**Describe the bug**
Remove stetho dependency from app

Parent Issue: #2907 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2910 

Changes: Removed stetho dependency

### CODE REVIEW

**Comment by codedsun** [comment]
@yashk2000 @iamareebjamal Merge this

**Comment by iamareebjamal** [comment]
Increment version code and name in other PR

**Comment by codedsun** [comment]
@iamareebjamal Let the travis pass and branch merges, I will send the PR asap.

**Comment by codedsun** [comment]
@iamareebjamal done merge please

**Pull request merged**
