### PR TITLE
Fixed Image Orientation problem

### LINKED ISSUE #1144: Image Not Viewing Properly while toggling between Landscape and Portrait
**Actual Behaviour**
2 images are shown instead of one while toggling between landscape and portrait and image is also not properly positioned.

**Expected Behaviour**

It should be properly positioned and viewed while switching between the landscape and portrait only that specific image should be viewed in that mode instead of two with distorted positions.

**Steps to reproduce it**
Go to a folder open image now change mode to landscape and then to portrait.

**LogCat for the issue**

09-15 02:15:35.993 7870-7870/org.fossasia.phimpme I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more.

**Screenshots of the issue**

screenshot_2017-09-15-02-10-13

**Would you like to work on the issue?**
Yes!

@mohitmanuja  @anantprsd5  kindly review the issue!

### PR DESCRIPTION
**Pull request by batbrain7**
Fix #1144 

Changes: 
The problem that was shown in the logcat as  : " org.fossasia.phimpme I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more."

This was because of the old version of the photoview which was not able to apprehend the null image. Now, I added a new better version of this photoview, which does not show this error. Also in the manifest the configchanges when set to orientation and the screenSize do not allow the programmable code to change the configuration. therefore fixed that too.
Now, the images on changing the orientation do are shown properly with appropriate resolution and no 
overlapping is seen in them as was before in the issue.

Screenshots for the change: 
screenshot_20171228-171826
screenshot_20171228-171850

### CODE REVIEW

**Comment by raj10071997** [comment]
@batbrain7- I am only giving a suggestion - why are you using this library - https://github.com/davemorrissey/subsampling-scale-image-view . Just handle the orientation changes as in the issue #1629 . Adding another library makes difficult to understand the code plus the developer has to understand the use of that library too.

**Comment by batbrain7** [comment]
@mohitmanuja @anantprsd5 @isuruAb please review

**Comment by anantprsd5** [comment]
@mohitmanuja Can you please take a look at this?

**Comment by batbrain7** [comment]
@raj10071997 if you carefully notice using the previous photoview package there is a logcat error as : 
"org.fossasia.phimpme I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more. "  This error was described in the issue #1144.
Due to this there were a lot more leaks during rotation. Also I did not add another library I replaced the contents of the previous photoview package with a new and updated photoview package, which is only better than the previous one and is not a redundant addition in this context, the addition is only better.

**Comment by raj10071997** [comment]
@batbrain7  I only referred to the android developers documentation about handling orientation changes. The documentation says that if you don't handle orientation by yourself the system does it for you by destroying and restarting your activity. But since in manifest file there was already an "orientation" tag for SingleMediaActivity and the onConfigurationChanged() method was already defined , so it was clear we have to handle the changes by ourselves.  Read the 4th paragraph in "Handling the Configuration Change Yourself" heading below the example. Here the link - https://developer.android.com/guide/topics/resources/runtime-changes.html . It clearly says that as the configuration changes the onConfigurartionChanged() method is called and by reading fields in the Configuration (object passed as parameter in the method), you can determine the new configuration and _make appropriate changes by updating the resources used in your interface_. So we needed to just update the resources. Also If you first rotate the phone in landscape mode then open the image in SingleMediaActivity , we can't see this issue which seemed to be a clear sign that we have to handle the configuration changes. That's why I was suggesting you that we have to only handle the configuration changes.

**Comment by batbrain7** [comment]
@raj10071997 I completely agree with you but also address the problem which is in the logcat : 
"org.fossasia.phimpme I/PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more."
which was pointed out by @codedsun.

**Comment by raj10071997** [comment]
@batbrain7  Actually if you see the file PhotoViewAttacher.java it's a log message and now read the "Remember" note "Handling the Configuration Change Yourself" heading it says - If you declare your activity to handle the orientation change and have images that should change between landscape and portrait, you must re-assign each resource to each element during onConfigurationChanged(). So when the configuration changes the imageView is destroyed by the system and that's why the log messages gets displayed in the logcat.

**Comment by batbrain7** [comment]
@anantprsd5  @isuruAb the changes in the PR are done as suggested, please review and merge this

**Comment by anantprsd5** [comment]
@batbrain7 The similar work was done before in another PR by @raj10071997 and I guess it has been merged and the issue is fixed. Next time onwards, I would suggest everyone to collaborate using the official Gitter channel if you are working on the same issue instead of sending different PR's. Thanks.

**Pull request closed without merging**
