### PR TITLE
Fix #1713 Modify description in slideshow dialog

### LINKED ISSUE #1713: Modify description in slideshow dialog
**Actual Behaviour**

Description in slideshow dialog is "Time interval (seconds)"

**Expected Behaviour**

Description should be "Time interval (seconds) (>1 sec)"

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashley8jain**
Fix #1713 

Changes: change the time interval message in edittext in slideshow dialog

Screenshots for the change: 
scree

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@ashley8jain Please do mention in the PR which issue it is addressing.

**Comment by ashley8jain** [comment]
@sauravvishal8797 there is no related issue. Just created PR directly

**Comment by sauravvishal8797** [comment]
@ashley8jain Please create an issue first before sending a PR.

**Comment by ashley8jain** [comment]
@sauravvishal8797 Done. Please review this

**Comment by ashley8jain** [comment]
@anantprsd5 @mohitmanuja @isuruAb @mariobehling Please merge this PR

**Comment by ashley8jain** [comment]
@anantprsd5 @mohitmanuja @isuruAb @mariobehling Please merge this PR

**Pull request merged**
