### PR TITLE
Fix #1960 - Caption is not shared to Instagram

### LINKED ISSUE #1960: Caption is not shared to Instagram
**Actual Behaviour**

While sharing the Image with caption to Instagram, Caption can not be shared as per Instagram Policy.

**Expected Behaviour**

User can be asked through the AlertDialog "Do you want to copy caption?", then user can paste the caption easily on Instagram.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashley8jain**
Fixed #1960 

Screenshots of the change:

### CODE REVIEW

**Comment by yashLadha** [comment]
The job of the user is not reduced at all.

**Comment by ashley8jain** [comment]
If user share to instagram, then he forgets that caption cant be shared to instagram, so user have to go back to phimpe app to copy caption and then again share to instagram.
Moreover, copy the caption takes times (press the pointer -> "SELECT ALL -> "COPY").

**Comment by yashLadha** [comment]
The intuitive thing user can also do to write in the Instagram app only
instead of phimpme, but user should write the caption in phimpme and that
has to be shared with instagram also. Hope you are getting the point.

**Comment by ashley8jain** [comment]
User can also write the caption on every app like whatsapp, facebook. But why is there caption on phimpme app?
Therefore, caption should be shared from instagram. If user want to write the caption directly on instagram, then he can press "No" in dialog title "Do you want to copy?".

**Comment by yashLadha** [comment]
I am also saying the same the app should share the caption and not the user
should copy paste the content, it seems like a clipboard managing app.

**Comment by ashley8jain** [comment]
Yeah caption cant be shared to instagram as per instagram policy, so caption can be copied automatically for easy & quick convenience

**Comment by yashLadha** [comment]
Them in that case there can be two choices:
1. Notify user that Instagram cannot share caption..and remove the text
field, because other apps are also following the same philosophy on play
store.
2. Update the message in alert dialog.
 If we think quantitatively how much work the user has to do them disabling
the edit text and displaying the toast of cannot share caption directly
will enable user to write only a single time, but in other case user has to
write and them paste the content also clicking on the alert dialog as well.
So number of actions are more in second option as compared to other. If we
think this way the number of action user have to perform for such a simple
task them it makes difference.

**Comment by ashley8jain** [comment]
@anantprsd5 @isuruAb what do you think?

**Pull request merged**
