### PR TITLE
redundant camera dialog removed

### LINKED ISSUE #2416: redundant camera dialog
**Actual Behaviour**

after resetting the settings, a dialog appears while opening up the camera settings for the first time which navigates to the camera.

**Expected Behaviour**

after resetting camera settings should be displayed directly without any dialog.

**Steps to reproduce it**

reset the settings. navigate to camera settings. a dialog would appear which directs to camera on clicking ok.

**Screenshots of the issue**

whatsapp image 2019-01-19 at 14 27 17

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2416 

Changes:
camera dialog after resetting settings removed.

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@kk63852 Pleaser resolve the conflicts.

**Comment by kk63852** [comment]
> @kk63852 Pleaser resolve the conflicts.

conflict resolved @sauravvishal8797

**Comment by mariobehling** [comment]
Please resolve conflicts. Thanks.

**Comment by mariobehling** [comment]
Unfortunately this PR was not getting resolved. Thanks anyways for learning about Open Technologies. Hope to collaborate again in future! Closing this due to inactivity.

**Pull request closed without merging**
