### PR TITLE
Fixed #290 Images should be scrollable

### LINKED ISSUE #290: Feature : Local Gallery images should be scrollable
**Actual Behaviour**
The user is not able to scroll to more images by swiping left and right. They have to go back and select another image.

**Expected Behaviour**

The user should able to scroll to more images by swiping left and right. 

**Steps to reproduce it**

Click on any image from local gallery and try to swipe right and left.

**Screenshots of the issue**

screenshot_2017-04-02-14-25-54-897_vn mbm phimp me
screenshot_2017-04-02-14-26-22-703_vn mbm phimp me

**Would you like to work on the issue?**

Yes. @Abhi2424shek @pa1pal  Please review.

### PR DESCRIPTION
**Pull request by mohitmanuja**
#290 

Changes: Now user can able to scroll images in local gallery.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @mohitmanuja we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/mohitmanuja/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mohitmanuja** [comment]
@Abhi2424shek please review it.

**Comment by Abhi2424shek** [comment]
Please check the failing tests.

**Comment by mohitmanuja** [comment]
@Abhi2424shek Resolved.

**Comment by pa1pal** [comment]
@mohitmanuja The PR showing opened from unknown repository? Did you delete the branch?

**Comment by mohitmanuja** [comment]
@pa1pal I am closing this PR and sending it again.

**Pull request closed without merging**
