### PR TITLE
Fixes #1738 Album(s) remain at fixed position when pinned

### LINKED ISSUE #1738: The album doesn't remain at the same position when pinned to top.
**Actual Behaviour**

When you pin the album to top, after refreshing the layout by swiping down, the album changes the position.

**Expected Behaviour**

The album shouldn't change the position.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by raj10071997**
Fixed #1738

Changes: First, if you pin only one album to the top and refresh the layout by swiping down the first album displayed is Phimp.me and not the one we pinned at the top. And if you pin multiple album at the top and they are arranged in order of the time they are pinned. But as soon as you swipe down , same Phimp.me album is displayed first which is not pinned. But now this doesn't happen, the pinned albums remain at their position even after refreshing the layout.

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
Please update the branch to the latest changes.

**Comment by raj10071997** [comment]
@abishekvashok  You can merge this branch I have updated it.

**Comment by raj10071997** [comment]
@abishekvashok @anantprsd5 @isuruAb Please review this branch. I have updated it.

**Comment by raj10071997** [comment]
@isuruAb @abishekvashok Please close this approved PR. It has been pending for a long time.

**Pull request merged**
