### PR TITLE
chore(deps): Bump gradle from 3.5.0 to 3.5.2

### LINKED ISSUE #2906: Gradle Version needs to be Updated in build.gradle file
**Describe the chore**
Gradle version Needs to be Updated to latest from 3.5.0 to 3.5.2
**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by Rajchowdhury420**
Fixed #2906

Changes: Updated build.gradle file , Bumped the Gradle version from 3.5.0 to 3.5.2

Screenshots of the change:

### CODE REVIEW

**Comment by codedsun** [comment]
@Rajchowdhury420 Please read 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjh--n2mdXlAhWLA3IKHQ2qC1AQFjAAegQIABAB&url=https%3A%2F%2Fblog.fossasia.org%2Fopen-source-developer-guide-and-best-practices-at-fossasia%2F&usg=AOvVaw1szzuiHMmsqCtg1VGocPHu

**Comment by Rajchowdhury420** [comment]
Sir but I saw similar small fixes to be merged in FossAsia repos ! Can u
explain

**Comment by codedsun** [comment]
@Rajchowdhury420 Yes valid pull request are always merged, do give read on the above blog

You need to open an issue and send a PR tagged to that issue

also, your branch is out of date - please check https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch

Also did

**Comment by Rajchowdhury420** [comment]
M really sorry !

**Comment by codedsun** [comment]
@iamareebjamal No need to be sorry, we are always here to learn. Welcome to the community and the project. Do join the channels and get stared!

**Comment by Rajchowdhury420** [comment]
Thank you sir , it just I m a bit new to development I m just 17

**Comment by codedsun** [comment]
@Rajchowdhury420 - 
You need to open an issue also.

**Comment by Rajchowdhury420** [comment]
Okay

**Comment by Rajchowdhury420** [comment]
Please check it now

**Pull request merged**
