### PR TITLE
Fix #2558 Margin/Padding Left/Right changed to Start/End

### LINKED ISSUE #2558: xml has many occurrences of paddingLeft/Right, marginLeft/Right etc.
**Actual Behaviour**

There are many occurrences of paddingLeft/Right, marginLeft/Right etc.

**Expected Behaviour**

Left/Right should be replaced with Start/End to support RTL devices.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by neel1998**
Fixed #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Mention the files changed in the PR. Add here what changes were made in this issue and if possible provide links(Deploy/Preview Link).]

Screenshots of the change:

### CODE REVIEW

**Comment by kk63852** [comment]
this is clearly not the way to submit a pr. please refer the issue in point and also you should have asked author first before submitting a pr related to the issue.

**Comment by neel1998** [comment]
I am really sorry for my mistake. Will keep this in mind from the next time.

**Comment by neel1998** [comment]
Can I make the PR again with proper changes?

**Comment by kk63852** [comment]
> Can I make the PR again with proper changes?

you should ask the author for permissions regarding the issue.

**Comment by neel1998** [comment]
okay

**Comment by yashk2000** [comment]
@neel1998 I am working on this issue. Please close this pull request and always ask the author of the issue before sending a pull request if the author is an active contributor.

**Pull request closed without merging**
