### PR TITLE
#116 issue solved:Share app Feature added

### PR DESCRIPTION
**Pull request by optnio00**
Fixes issue #116

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change: 
screenshot_2017-03-14-17-44-14
screenshot_2017-03-14-17-44-22

### CODE REVIEW

**Comment by dynamitechetan** [comment]
I think it's not the correct placement for sharing option. We can add no more than 5 options in bottom navigation bar and we have map PR pending which is a important feature of the app. So place this somewhere else but not the bottom bar.

**Comment by optnio00** [comment]
ok i change the position . Now i will put it in settings tab

**Comment by Abhi2424shek** [comment]
Dont put it on settings.

**Comment by rohanagarwal94** [comment]
@optnio00 it is quite derogatory if you solve issues assigned to/ opened by other fellow contributors without their permission. @Abhi2424shek if you only could keep a check on this.

**Comment by heysadboy** [comment]
@optnio00 I think you should put share option in toolbar. In the for of those three dots on the right end.

**Pull request closed without merging**
