### PR TITLE
chore: Add fdroid product flavor

### PR DESCRIPTION
**Pull request by yashk2000**
- First attempt to add flavor to make an fdroid apk

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is no-op. Move the google dependencies to playStore and OSS dependencies to fdroid

**Comment by yashk2000** [comment]
@iamareebjamal the only google dependency  we are using is exoplayer right?
Rest of the dependencies are open source. And according to [this](https://f-droid.org/en/docs/FAQ_-_App_Developers/#which-libraries-and-dependencies-are-good-to-use) Android support repositories are allowed.

**Comment by iamareebjamal** [comment]
exoplayer is open source

**Comment by iamareebjamal** [comment]
Where are we using google-services.json? If we're not using it, remove it

**Comment by yashk2000** [comment]
@iamareebjamal I checked the dependencies. I did not find the declaration for google services there. Should I remove the file then?

**Comment by yashk2000** [comment]
@iamareebjamal https://github.com/fossasia/phimpme-android/pull/2835

**Comment by iamareebjamal** [comment]
Then we are not using any proprietary library. Let's close this and prepare adding to F-Droid. You'll have to see what other apps using OpenCV do and add a download and moving step in between

**Comment by yashk2000** [comment]
@iamareebjamal we cannot add the app directly to fdroid? OpenCV is open source.

**Comment by iamareebjamal** [comment]
```
git clone https://github.com/fossasia/phimpme-android
cd phimpme-android
./gradlew assembleRelease
```

Run these commands and tell me the output. This is what fdroid will run. If this runs without any error, then yes, you can add the app directly in fdroid

**Comment by yashk2000** [comment]
On it.

**Comment by yashk2000** [comment]
@iamareebjamal we need to add the other files, `jniLibs`, `staticlibs`, `3rdparty` and `jni/include` too.

**Comment by iamareebjamal** [comment]
> You'll have to see what other apps using OpenCV do and add a download and moving step in between

Exactly what I said before

**Comment by yashk2000** [comment]
There used to be an app called OpenCV manager, but it is no longer there. I'll hunt for more ways to use OpenCV today afternoon. 
I'm sorry for the delay because of my college periodical exams this week. I'll compensate for it in the coming week.

**Comment by iamareebjamal** [comment]
This dicussion should be in #1181

**Pull request closed without merging**
