### PR TITLE
Fixes image view in photoActivity

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #588 Photos not appearing properly in photoActivity.

Changes: Added layout gravity as center and deleted layout land as it was not required.

Screenshots for the change: 
screenshot_20170615-024534

### CODE REVIEW

**Comment by vinaysajjanapu** [comment]
@anantprsd5 there is a lot of empty space around the picture. Wouldn't it be better if you scale the preview to proper size on the screen? I mean having a fixed preview height for pictures of all resolutions. 
screenshot_2017-06-14-04-26-19-792_vn mbm phimp me

**Comment by anantprsd5** [comment]
Okay. Will make the changes soon.

**Comment by anantprsd5** [comment]
@vinaysajjanapu @pa1pal Done with all the changes.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 preview image is getting distorted. change layout_width value to wrap_content

**Comment by anantprsd5** [comment]
@vinaysajjanapu changing width to match_parent won't help. The low resolution images will be displayed like a vertical line then.

**Comment by anantprsd5** [comment]
I have done it programmatically. Please review.

**Comment by vinaysajjanapu** [comment]
Instead of doing programatically, you can do that in a much simpler way. 
just change 
```
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitCenter"
```
these attributes of PhotoView in activity_photo.xml
and change layout-land accordingly.

**Comment by anantprsd5** [comment]
@vinaysajjanapu Done. Thanks.

**Pull request merged**
