### PR TITLE
Fix for issue#2384: Replaced Toasts with SnackBars.

### LINKED ISSUE #2384: Replacing Toasts with SnackBars.
**Actual Behaviour**

In several activities, toasts are displayed as notifications.

**Expected Behaviour**

Instead of toasts, snackbars should be shown. Toasts cannot be canceled and continue to be displayed even if the app is closed or activity is shifted.

**Steps to reproduce it**

1) Turn off the internet and go to accounts settings. Tap on any button. A toast is shown.
2) Go to security settings to set a password. Press on the cancel button. A toast is shown.
3) There are several more examples.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2384 

Changes: Toasts have been replaced with SnackBars wherever a SnackBar is more appropriate than a Toast.

Some of the screenshots of the change are : 

screencap3
screencap2
screencap1
screencap

### CODE REVIEW

**Comment by abishekvashok** [comment]
The last screenshot needs fixing

**Comment by abishekvashok** [comment]
Approving as it's not related to the issue I mentikned

**Comment by yashk2000** [comment]
> The last screenshot needs fixing

@abishekvashok should I make a separate issue for it once this pull request is merged?

**Comment by abishekvashok** [comment]
Yep

**Pull request merged**
