### PR TITLE
fix: removed materialshowcase libary due to crash on android 10

### LINKED ISSUE #2930: Phimp.me app crashed on opeing. Android 8.1.0 #2930
#2930
**Describe the bug**
Installed the app from Playstore. 
Opened just once and explored, after that it fails to open. 
I've attached the screenshot of logs. Corrections are welcome.

**Screenshots**
Screenshot_2019-11-22-19-58-56-404_com miui bugreport
Screenshot_2019-11-22-19-58-59-110_com miui bugreport

Device - Redmi Note 5 Pro
Android Version - 8.1.0

### PR DESCRIPTION
**Pull request by codedsun**
Fixed #2930 

Changes: Removed material showcase library

Screenshots of the change:

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal @yashk2000 Please check and merge!

**Comment by codedsun** [comment]
@iamareebjamal Please get this done

**Comment by iamareebjamal** [comment]
Should have replaced with some other library

**Comment by codedsun** [comment]
@iamareebjamal Shall I do this in this PR or another issue?

**Comment by iamareebjamal** [comment]
Why would I merge a PR on which I have requested changes and which would leave the app in a broken state?

**Comment by codedsun** [comment]
Why should this leave the app in broken state? It has removed the library but not replaced with some other, but didn't broke anything. @iamareebjamal

**Comment by iamareebjamal** [comment]
That's called broken. Every commit of the repo should have correct build of app. This is clearly incomplete work, so should not be merged as a commit, regardless of if it breaks something or not.

If you just add a blank activity and say nothing is broken, and I'll add UI in another PR and logic in yet another PR, none of those PRs should be merged because the feature is incomplete and if the user will compile the app from a particular commit, he/she'll get an incomplete app, doesn't matter if the app crashes or not

**Comment by codedsun** [comment]
@iamareebjamal Okay sending the PR asap

**Comment by codedsun** [comment]
ezgif com-video-to-gif-3

**Comment by codedsun** [comment]
ezgif com-video-to-gif-5

**Comment by codedsun** [comment]
ezgif com-optimize

**Comment by codedsun** [comment]
https://gifyu.com/image/vcHx

@iamareebjamal Check this now

**Pull request merged**
