### PR TITLE
deleting from favourite now requires selecting an image first

### LINKED ISSUE #2485: favourite photos remove from favourites option issue
**Actual Behaviour**

when remove from favourites option is executed, it removes all the media from the favourite folder even when no media is selected.

**Expected Behaviour**

only when some media is selected then this option should be executed.

**Steps to reproduce it**

add some media to favourite folder. navigate to favourite photos folder and tap on delete option when no media is selected from the folder. all the images would be removed from favourite without selecting them.

**Would you like to work on the issue?**
yes.

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2485 

Changes:
delete action made invisible unless some media is selected.

### CODE REVIEW

**Comment by angmas1** [comment]
When no images were selected, that button removed all images from favorites which I think served a purpose but wasn't clear for the user. Either you should change the dialog text when delete button is pressed to ask for removing all the photos from favorites or you should make the delete button disappear when no photos are selected.

**Comment by angmas1** [comment]
Okay, then why not make delete button disappear when no photos are selected i.e. when not in editmode

**Comment by kk63852** [comment]
okay i'll make the changes.

**Comment by kk63852** [comment]
i tried making it disappear but to make it disappear it will need a lot of unnecessary code change because favorite album has no separate code, it shares its menu item with album mode.
the message could be changed but the response would be the same that is it would empty the folder if no media is selected but upon selecting some media is it will be deleted by performing this action. therefore i think its better this way only. @angmas1

**Comment by angmas1** [comment]
Okay, no problem.

**Comment by abishekvashok** [comment]
> i tried making it disappear but to make it disappear it will need a lot of unnecessary code change because favorite album has no separate code, it shares its menu item with album mode.
the message could be changed but the response would be the same that is it would empty the folder if no media is selected but upon selecting some media is it will be deleted by performing this action. therefore i think its better this way only. @angmas1

Then we could just remove this PR and the issue. Bcz, I expect the trash button to remove all favourites. Displaying the button and displaying an alert saying that you need to select before you click, is not a good UI.

**Comment by kk63852** [comment]
@abishekvashok i made the delete button invisible unless some media is selected.

**Pull request merged**
