### PR TITLE
chore: Updated update-apk script

### LINKED ISSUE #2303: Fix and implement additional app builds in apk branch
We need apks of master and dev branch in the apk branch. Please implement them as follows:
* Build apks of dev branch and deploy them apk branch on merged commits (of dev branch)
* Build apks of master branch and deploy them in the apk branch on merged commits (of master branch)
* only overwrite the builds of the specific branch (master or dev). When dev branch builds are created they should not rebuild the master branch apks in the branch for example.
* Create a specific Readme.md in the apk branch explaining the process.

Naming conventions
* phimpme-dev-debug.apk	
* phimpme-dev-release.apk
* phimpme-master-debug.apk
* phimpme-master-release.apk
* phimpme-release.apk

References:
* Compare with https://github.com/fossasia/neurolab-android/tree/apk

### LINKED ISSUE #2797: Fix the auto release script.
**Describe the chore**
Fix the auto release script.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2797 
Fixed #2303 

Changes: Simplifies signing of apk.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic please review.

**Comment by iamareebjamal** [comment]
No change done in prep-key

**Comment by yashk2000** [comment]
@iamareebjamal is this fine?

**Comment by yashk2000** [comment]
@iamareebjamal please merge if this is fine.

**Pull request merged**
