### PR TITLE
fixed the customize viewer dialog issue.

### LINKED ISSUE #2690: customize viewer dialog looks awkward.
**Describe the bug**

the dialog appearance is really when the switch button is turned on or off.
**To Reproduce**

1. Go to settings.
2. Click on customize viewer.
3. the dialog appearance is really awkward when the switch is turned on or off.

**Expected behavior**

dialog appearance should be improved.

**Screenshots**

ezgif com-video-to-gif (1)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2690 

Changes: changed the customize viewer dialog appearance.

Screenshots of the change: 
ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by sparrow007** [comment]
@kk63852 would you please describe what you have changed?

**Comment by kk63852** [comment]
> @kk63852 would you please describe what you have changed?

earlier the transparency text and its sub text were not visible when the button was turned off. there was also orientation issue and an extra linear layout which needed to be removed.

**Comment by abishekvashok** [comment]
Resolve conflicts and let's merge this

**Comment by kk63852** [comment]
> Resolve conflicts and let's merge this

conflict resolved. @abishekvashok

**Pull request merged**
