### PR TITLE
Fix #1896-Proper images displayed on performing click ope…

### LINKED ISSUE #1896: Issues in opening images from upload history.
**Actual Behaviour**

Clicking on an image in the Upload History section, a different image opens up than the one clicked. A single image is displayed on clicking/opening any no of images.
No option to slide to the other images in the upload history section, the user has to go back and click on other images to open them.
Options such as copy, move, slideshow, make album cover are visible on opening the images from upload history.

**Expected Behaviour**

- [ ] Proper image should be displayed on performing the click operation. Sliding to other images should be enabled, just like it is there in the albums, favourites etc. 

- [ ] Options such as copy, move, slideshow etc are not required as upload history section is only to keep track of the images shared.

**Steps to reproduce it**

Go to the upload history section, click/open any number of images.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
…ration, Slide to other images enabled.

Fix #1896 

Changes: Proper images are displayed via the SingleMediaActivity on performing click operation on the images present in the upload history section, Slide to other images are enabled i.e users will be able to move to other images in the upload history by sliding.
Gif before change:
videotogif_2018 05 19_21 57 56

GIF after change:
videotogif_2018 05 19_21 42 52

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@abishekvashok @isuruAb @anantprsd5  Please review.

**Comment by sauravvishal8797** [comment]
@abishekvashok Solved both the parts, please review.

**Comment by sauravvishal8797** [comment]
@abishekvashok Did the changes, please review.

**Comment by sauravvishal8797** [comment]
@abishekvashok @anantprsd5 @isuruAb Please review this PR.

**Comment by sauravvishal8797** [comment]
@anantprsd5 @iamareebjamal @Subhankar29 @the-dagger @vanhonit Please review.

**Comment by mariobehling** [comment]
Please provide before/after screenshot or gif to show the changes.

**Comment by mariobehling** [comment]
Please resolve merge conflicts.

**Pull request merged**
