### PR TITLE
Filter in Accounts

### LINKED ISSUE #1946: Filter in Accounts [Featue]
Search bar in accounts helps the user to search the accounts easily .
screenshot_2018-03-10-17-13-08-625_org fossasia phimpme

### PR DESCRIPTION
**Pull request by Ananthusubramanian**
Fixed #1946

I have changed the adapter to accept a list so as to get the data faster and make it filtered.If it uses the realm , the realm database cannot be accessed in a new thread that is the filter class .

Screenshots of the change: 

screenshot_2018-03-10-17-13-08-625_org fossasia phimpme

### CODE REVIEW

**Comment by DhruvamSharma** [comment]
Why is it required?

**Comment by Ananthusubramanian** [comment]
@DhruvamSharma  This will filter the accounts easily and the signed in account will be shown at the top of list and the other accounts below them.

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian Please update the branch.

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian I don't think we need this at the moment. However, if you'd like to work on this, feel free to ask me to reopen this issue.

**Pull request closed without merging**
