### PR TITLE
Fix #1174 Camera View Icons Updated

### LINKED ISSUE #1174: Changing the background of Filter Icon and Switch Camera Icon
**Actual Behaviour**

The filter icon and switch camera icon are not visible with a white background image.

**Expected Behaviour**

In Camera View, Filter Icon and Switch Camera icon should be provided with black/grey background and circular image button can be used instead of image button as while rendering an image which has a white background, these icons are not visible to the user.

**Steps to reproduce it**
Open Camera ,switch to front or render  white background /daylight.

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fix #1174  Icons Color Updated 

Changes: I changed the icon of the filter icon and switch camera and updated it to a more good one which is also visible in dim and bright light but previously were not visible.

Screenshots for the change: 
screenshot_2017-09-21-02-27-49

@anantprsd5 Kindly review !

### CODE REVIEW

**Comment by codedsun** [comment]
@vinaysajjanapu kindly review

**Comment by codedsun** [comment]
@mohitmanuja  Kindly review!

**Comment by vinaysajjanapu** [comment]
@codedsun Can you add a screenshot with some colored preview (not black)?

**Comment by codedsun** [comment]
@vinaysajjanapu  jst a minute!

**Comment by codedsun** [comment]
screenshot_2017-09-23-19-07-16

screenshot_2017-09-23-19-11-17

 Check this @vinaysajjanapu

**Comment by codedsun** [comment]
@vinaysajjanapu that background can be white too..but that's was the issue we were dealing it isn't visible when you are in bright light

**Comment by codedsun** [comment]
@vinaysajjanapu white can be chnaged to something like light grey.

**Comment by vinaysajjanapu** [comment]
I don't see much significance in the issue you are referring. I've seen the same happening in few other famous camera apps as well.
If we make it light gray, then it becomes odd. We'll have to change the color of other icons as well. Light gray is generally less visible in most cases than white. So it is not preferred.

The new icons are good (use white effects icon). Replace all the png icon images in the camera page to vector drawables in this PR itself.

**Comment by codedsun** [comment]
@vinaysajjanapu all the images with single vector xml or corresponding to each size ,each xml?

**Comment by vinaysajjanapu** [comment]
A single vector image will be sufficient.
The same vector can be used for very small sizes and extremely large sizes. It won't get pixelated like pngs/jpgs.

**Comment by codedsun** [comment]
@vinaysajjanapu I made the changes kindly review the PR.A single vector image is used of 48dp .

**Pull request merged**
