### PR TITLE
Fix #1560 Resize Grid layout[Album+media list] using pinch gesture

### LINKED ISSUE #1560: Resize Grid layout[Album+media list] using pinch gesture
**Actual Behaviour**

No. of column [in Album + Media grid list] can be change through Settings.

**Expected Behaviour**

User should resize the grid layout easily using pinch gesture.(this feature is used in Google Photos)

**Steps to reproduce it**

[Doc](http://wiki.workassis.com/pinch-zoom-in-recycler-view/)
* Add Pinch Gesture
* Link this gesture with grid layout as spanCount.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashley8jain**
Fix #1560

Changes: resize the grid layout easily using pinch gesture.(this feature is used in Google Photos)
[Doc](http://wiki.workassis.com/pinch-zoom-in-recycler-view/)

screencast1 1

### CODE REVIEW

**Comment by ashley8jain** [comment]
@anantprsd5 @mohitmanuja Please review this

**Comment by ashley8jain** [comment]
@mayank8318 @codedsun Review this

**Comment by codedsun** [comment]
@ashley8jain I would like to have comments more from @anantprsd5 @mohitmanuja as they are collaborators, and what I think is that it's good but the app currently now is having more lags and issues which are at a priority than this. This can be merged when we get ready with them.
@mayank8318 @nikit19 @sauravvishal8797 Kindly drop in ur views too.

**Comment by nikit19** [comment]
Well I think it is a good feature and it won't affect any of the existing issues

**Comment by ashley8jain** [comment]
@anantprsd5 Done. Kindly review the changes please

**Pull request merged**
