### PR TITLE
Fixes issue #376 & #394: Timer Implemented and Camera layout updated

### PR DESCRIPTION
**Pull request by AliAyub007**
Fixes issue #376 & #394 

Changes:
Timer Added and Camera Layout Updated

Screenshots for the change:

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @AliAyub007 we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/AliAyub007/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Abhi2424shek** [comment]
Hi, please try to solve only one issue per PR from the next PR, it makes reviewing a lot more easier. :)

**Comment by AliAyub007** [comment]
@Abhi2424shek  Sure I will do it in that way and sorry for the inconvenience caused.

**Comment by pa1pal** [comment]
@AliAyub007 if I enable timer once. It then click every photo with timer, irrespective of the state of the button.

**Comment by AliAyub007** [comment]
@pa1pal  It's working fine. I checked it before and even I checked it now.

**Comment by pa1pal** [comment]
camera

**Comment by AliAyub007** [comment]
@pa1pal  It is showing this on my device as I have set text to empty string in onFinish() function

18120039_794262314058211_852463615_o


18175832_794261957391580_1003240451_o 1

**Comment by pa1pal** [comment]
Works fine if I click a image. Close app and reopen again. 
If clicking again and again not updating the status of timer.

**Comment by AliAyub007** [comment]
@pa1pal Kindly review it now. I hope it is working fine now. :)

**Comment by AliAyub007** [comment]
@pa1pal still there is a bug. I will fix it soon and commit.

**Comment by AliAyub007** [comment]
@pa1pal  there is this same issue with shutter sound button. Should I do this within this commit or open a new issue for that? It's just a switch case.

**Comment by pa1pal** [comment]
so do in this only.

**Pull request merged**
