### PR TITLE
Adding Recyclerview to show connected Accounts list

### PR DESCRIPTION
**Pull request by pa1pal**
Fixes issue #541 

Changes: Adding a recycler view to show connected accounts details such as Full name, username and avatar. Test demo shown in the screenshot. Where a small indicator will show the account logo, such as twitter in screenshot. Main profile photo, username and full name.

account_manager_list

When database work will be complete then we can access the data from the database and show it in the list.

### CODE REVIEW

**Comment by Subhankar29** [comment]
@pa1pal You have added Wordpress in the add account. I think that will take some time to implement because there is no direct way of integrating it like in Facebook and Twitter. So, we can add it in later stages.

**Comment by pa1pal** [comment]
@Subhankar29 yes sure.

**Comment by pa1pal** [comment]
@mohitmanuja @anantprsd5 @Subhankar29 @vinaysajjanapu Please review.

**Comment by pa1pal** [comment]
@mohitmanuja @anantprsd5 @Subhankar29 @vinaysajjanapu Please review.

**Pull request merged**
