### PR TITLE
Fix #2194 app crashes in crop fragment depends on orientation

### LINKED ISSUE #2194: App crashes if the orientation is changed when click on the crop of the image
**Actual Behaviour**

App crashes if click on crop (Transform section) and then on orientation change.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

Step 1. Click on edit button of the image and select the transform section.

Step 2. Click on crop button and changed the orientation without saving it then app will crash.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sparrow007**
Fixed #2194 

Changes: [crash due to calling the null bitmap because of changing the orientation so i apply few conditions in order to stop the app crashes.]

GIF  of the change:

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you make it work in a way that, the crop function still remains on the same state, instead of resetting?

**Comment by sparrow007** [comment]
yeah i will try for that but i send this PR just to stop crash in the app.

**Comment by sparrow007** [comment]
I am going to create new issue for that and work on it.

**Comment by abishekvashok** [comment]
> I am going to create new issue for that and work on it.

Nope, please do it in this PR itself.

**Comment by abishekvashok** [comment]
Updates?

**Comment by sparrow007** [comment]
@abishekvashok  I am working on it , i will give you update soon.

**Comment by sparrow007** [comment]
@abishekvashok  PR #2231 fix it (PR makes the cropFragment remain in it first position) although it's not remain in state which is changes in crop position in portrait mode will also remain same that is the case of this issue #2175 but it will appear crop rectangle after changes the orientation.

**Comment by abishekvashok** [comment]
Please fix it completely.

**Comment by codepoet2017390** [comment]
> I am ready with the fix for #2175 will put it up by tonight
> Please fix it completely.

@abishekvashok 
This is regarding Fix for Issue #2175  and the feature for retention of state when edit is not saved. I have fixed Issue #2175 and i'm halfway through to fix the other issue. Small bugs keep creeping in when i try to fix these issues as they are spread over a large number of activities. So i need some time and i assure a quality fix to it.

**Comment by abishekvashok** [comment]
Take your own time

**Pull request merged**
