### PR TITLE
Material design and #66 issue

### PR DESCRIPTION
**Pull request by optnio00**
Fixes issue #66 

Changes: 1. Material design UI
                2.Intro slider 
                3. new splash screen

Screenshots for the change: 
screenshot_2017-03-06-19-21-55
screenshot_2017-03-06-19-22-02
screenshot_2017-03-06-19-22-07
screenshot_2017-03-06-19-22-27
screenshot_2017-03-06-19-21-52

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
Hey, pls get good icons, it's a bit distorted, center the text, the photo image in the right side of the red screen looks bad,  add proper distance between two vertical textViews.

**Comment by Abhi2424shek** [comment]
Resolve the conflicts and besure from next time to send one PR with one commit for one issue! :)

**Comment by devkhan** [comment]
Correct me if I'm wrong, but why should there be a splash screen if there is no long processing task to be done before showing the home?

**Comment by dynamitechetan** [comment]
@devkhan I was going to say that. I don't think that there should be a splash screen just for sake of having it.

**Comment by pa1pal** [comment]
This is getting stale. Reopen with multiple PRs for different issues.

**Comment by Abhi2424shek** [comment]
@optnio00 I am closing this, it would be better if you could work on from the latest tree. However if you insist on working in this PR, you are free to open it.

**Pull request closed without merging**
