### PR TITLE
Fixes 1 of #162 Implement Tap to focus

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue : Implement Tap to focus

Changes: Added Tap to focus functionality.

### CODE REVIEW

**Comment by anantprsd5** [comment]
@Abhi2424shek @pa1pal please review.

**Comment by pa1pal** [comment]
@anantprsd5 I reviewed it works fine.
Just quickly add a brief description of the functions you added in the file.

**Comment by anantprsd5** [comment]
@pa1pal focusOnTouch is to focus on the tapped region
calculateFocusArea and clamp is just used for focus area calculation which is passed on to rect.

**Comment by pa1pal** [comment]
@anantprsd5 This is fine. 
I want you to commit these changes, write this above function.

**Comment by anantprsd5** [comment]
@pa1pal Oh. Sure.

**Comment by anantprsd5** [comment]
@pa1pal Done. Thanks :+1:

**Pull request merged**
