### PR TITLE
Status bar managment in Camera

### PR DESCRIPTION
**Pull request by heysadboy**
Solving issue #187

### CODE REVIEW

**Comment by heysadboy** [comment]
@pa1pal @Abhi2424shek Please see.

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @heysadboy we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/heysadboy/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Abhi2424shek** [comment]
Conflicts @heysadboy the dev setup has been made easier now.

**Comment by heysadboy** [comment]
@Abhi2424shek Okay, done.

**Pull request merged**
