### PR TITLE
1/2 hard coded strings removed upto settings activity.

### LINKED ISSUE #2658: hardcoded strings at many places.
**Describe the bug**

there are many hard-coded strings in the app code like messages, keys, name etc.

**Expected behavior**

the hardcoded strings should be saved in strings xml.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by kk63852**
Fixed #2658 

Changes: 
1/2:  hard coded strings removed upto settings activity.

### CODE REVIEW

**Comment by kk63852** [comment]
i'll adding more commits to this pr as this is not solved yet. @abishekvashok @sauravvishal8797

**Comment by yashk2000** [comment]
It's good that you'll keep adding more commits, but why open a pull request if the work is not complete? You should have opened the pull request only after completely fixing the issue.

**Comment by kk63852** [comment]
This issue has a lot of line change. That's why i thought instead of having one large conmit, i would divide it into multiple commits.

**Comment by yashk2000** [comment]
But the pr to merged will be this one.. you'll be squashing all commits in the end anyway. When I was removing hardcoded dimensions from xml files, I also made a large amount of changes, but I sent a single pull request at one time. You should make a pull request only after the issue you're fixing is completely fixed. There is no point in opening a half completed pr as it won't be merged until it is completed.

**Comment by kk63852** [comment]
I will see to it. Thanks for you suggestion.

**Comment by yashk2000** [comment]
@iadeelzafar this pr isn't completed yet. When it is completed, the commits will be squashed by the creator.

**Comment by iadeelzafar** [comment]
@yashk2000 Amending into previous commit is the best candidate for such use-cases. Why create a lot of commits(then squashing) for the same logical change when you can simply amend it. Squashing is preferred when you're going for a feature which needs different commits and at the end you need to squash them.

**Pull request closed without merging**
