### PR TITLE
Fix #1381 Refwatcher added

### LINKED ISSUE #1381: Adding RefWatcher of LeakCanary to Fragments
**Actual Behaviour**
The leak canary couldn't detect leaks from fragments, hence refwatcher need to be added.

**Expected Behaviour**

After refwatcher is added, the app will be able to detect leaks in fragments also.

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fix #1381 

Changes: Made the Refwatcher in Application Class and added to watch in all the fragments present.

Screenshots for the change: 

@aditya98ak @mayank8318 @mohitmanuja @anantprsd5 @sridharjajoo Please review!

### CODE REVIEW

**Comment by sridharjajoo** [comment]
@codedsun There are a lot of extra lines.Try to delete those.

**Comment by mariobehling** [comment]
Thanks for the additional PR. Please also help to stabilize the app and keep the number of PRs manageable by working with co-developers to get existing PRs merged first before submitting new PRs. Let's work together as a team.

**Comment by mayank8318** [comment]
@codedsun :+1:  to what @sridharjajoo said.

**Comment by codedsun** [comment]
Kindly, check now! @sridharjajoo @mayank8318

**Comment by codedsun** [comment]
@mariobehling Merge this !

**Pull request merged**
