### PR TITLE
Contribution Guidelines

### PR DESCRIPTION
**Pull request by heysadboy**
Fixing issue https://github.com/fossasia/phimpme-android/issues/51

### CODE REVIEW

**Comment by anantprsd5** [comment]
@heysadboy Hey, Please squash your commits, three commits are there currently. Thanks.

**Comment by heysadboy** [comment]
@anantprsd5 Okay, I did it.

**Comment by anantprsd5** [comment]
@heysadboy Just a suggestion, Wouldn't it be great if we can add something like a commit message format in the contributing.md file to keep the standards of the commit messages. Something like
'''
 Fixes issue #[issue number] [Description of the issue]
'''

**Comment by anantprsd5** [comment]
@heysadboy Just a suggestion. Wouldn't it be good if we can add a commit message format in this to keep the standards of the commit messages. Something like
    Fixes #[issue number] [Description of the issue]
Just like other Fossasia projects

**Comment by heysadboy** [comment]
@anantprsd5 Hey, I described to mention the respective issue in the pull request.

**Comment by anantprsd5** [comment]
@heysadboy Yeah, but that would be the comment, I was talking about the commit messages.

**Comment by Abhi2424shek** [comment]
Yea pls include commit message guidelines.

**Comment by heysadboy** [comment]
@Abhi2424shek Okay got it 👍

**Pull request merged**
