### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kundan28**
Fixed #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Mention the files changed in the PR. Add here what changes were made in this issue and if possible provide links(Deploy/Preview Link).]

Screenshots of the change: 
image

### CODE REVIEW

**Comment by Kundan28** [comment]
@abishekvashok If you use the ‘New Documentation’, it's not possible to center a table (since the table takes a full width of the column).

**Comment by abishekvashok** [comment]
Make that table full screen then.

**Comment by Kundan28** [comment]
To do so we have to use CSS for that.

**Comment by abishekvashok** [comment]
And case doesn't work with GitHub, they have a sanitizer.

**Comment by abishekvashok** [comment]
Let's merge it then

**Comment by abishekvashok** [comment]
Thank you!

**Comment by Kundan28** [comment]
@abishekvashok  Most welcome.

**Pull request merged**
