### PR TITLE
Fixed the circle reveal animation on top bar.

### LINKED ISSUE #1928: Exit reveal animation is not working properly
**Actual Behaviour**

The exit reveal is showing the next toolbar before closing the animation.

**Expected Behaviour**

The next toolbar should be displayed either after the animation or along with animation.

**Steps to reproduce it**
Click on close button while selecting any image from album.

**Screenshots of the issue**

https://drive.google.com/open?id=1r5bziQ0vsHkaU8kMna7aZNANYvWi3vKr

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by yashLadha**
Fixed #1928 

Changes: Changed the exit reveal with start reveal for a better animation.

Changes can be seen from the following video: 

https://drive.google.com/open?id=1Mrtp16ZXgHlHKJC9DKVzuY92GaDj-yxC

### CODE REVIEW

**Comment by DhruvamSharma** [comment]
Nice work done.

**Comment by abishekvashok** [comment]
Great work!

**Comment by yashLadha** [comment]
Branch Updated @abishekvashok .

**Comment by abishekvashok** [comment]
There were still to go.

**Pull request merged**
