### PR TITLE
added screenshots with frame

### LINKED ISSUE #2187: improve UX in readme file by adding a mobile frame to screenshots
**this is the kind of screenshots we are using currently**

ss_1

**readme will look a lot better if we use this kind of screenshots**

ss_1

**Would you like to work on the issue?**
yes

please assign this issue to me

### PR DESCRIPTION
**Pull request by prudhvir3ddy**
Fixed #2187 

Changes: changed files in docs/_static/screenshots

### CODE REVIEW

**Comment by abishekvashok** [comment]
Can you remove the blue backgrounds?

**Comment by prudhvir3ddy** [comment]
@abishekvashok  default is no backgrounds .i added blue background so that it can match our app logo .

isn't that looking good ? i will change it if not

**Comment by abishekvashok** [comment]
The second one looks fine, can you add the same?

**Comment by prudhvir3ddy** [comment]
@abishekvashok  done added . please review

**Comment by abishekvashok** [comment]
Updates?

**Comment by prudhvir3ddy** [comment]
@abishekvashok done couldn't update second screenshot check out https://github.com/prudhvir3ddy/phimpme-android here how this is looking now , i added screenshots from my phone

**Comment by prudhvir3ddy** [comment]
@abishekvashok  done

**Pull request merged**
