### PR TITLE
Wordpress Integration file with volley library

### PR DESCRIPTION
**Pull request by deepakbansal168**
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
Pls resolve the conflicts your fork seems to be behind.

**Comment by harsu-ag** [comment]
@deepakbansal168 the authentication system used works only as ann client owner as mentioned in https://developer.wordpress.com/docs/oauth2/ 

Can I work on changing the authentication. ?

**Comment by harsu-ag** [comment]
I have done the OAuth part but needed some help regarding committing my changes to this PR. 

I tried sending a PR to `deepakbansal168:development` fork, but I am unable to as I have forked the base branch. So, do I need a write access to the fork to directly commit my changes to this branch?

**Comment by Abhi2424shek** [comment]
Yes, to directly commit you would need wrote access, however you could also sent a PR to his development branch which if he accepts and merge would become a merge commit and be shown here like a regular commit. @harsu-ag

**Comment by harsu-ag** [comment]
@Abhi2424shek I was not able to send a PR to his development branch. As I have already forked the fossasia project, I was not able to fork a deepak's fork. 
So, I asked for a write access. 😄

**Comment by deepakbansal168** [comment]
@harsu-ag i am still waiting for your update.

**Comment by Abhi2424shek** [comment]
@deepakbhansal seems like @harsu-ag is not near, can you work on it on your own please. This is a critical part of the app, would you be needing any help?

**Comment by rohanagarwal94** [comment]
@Abhi2424shek let me help out @deepakbansal168 with this.

**Comment by Abhi2424shek** [comment]
Sure have a try.

**Comment by mariobehling** [comment]
@deepakbansal168 Thanks for your contribution. Please help to resolve the conflicts.

**Comment by deepakbansal168** [comment]
sure i will resolve the conflicts.

**Comment by Abhi2424shek** [comment]
@rohanagarwal @deepakbhansal is waiting for you, any inputs please, it would be awesome.

**Comment by rohanagarwal94** [comment]
@Abhi2424shek it needs a lot of changes to bring this feature to execution. It requires me  maximum a day more to figure everything out before I create a PR. I would request to close this PR since this is not a native solution and is using webview. In fact this code is not even fetching the media of a particular wordpress website. I will send the PR as soon as possible.

**Comment by Abhi2424shek** [comment]
Please do work in collaboration with @deepakbhansal @rohanagarwal :) It would be better if you two could communicate together and decide to who's fork the changes will be pushed and work in Collaboration. Can you please do that?

**Comment by Abhi2424shek** [comment]
#343 is an updated version of this @deepakbhansal, @rohanagarwal and @deepakbhansal can you to work forward on this in #343 please, it would be much better to do so. Shall I close this or as this is becoming old.

**Comment by rohanagarwal94** [comment]
@Abhi2424shek please close this. Unfortunately, this is not the correct way to solve this problem. I have updated my PR. Would love everyone to contribute to it. It may require time to understand my code since I took help from the official Wordpress android, but it is the correct way to go.

**Comment by Abhi2424shek** [comment]
Ok @deepakbhansal please follow up there, closing this one.

**Pull request closed without merging**
