### PR TITLE
Fixed #1532: Added FB links

### LINKED ISSUE #1532: Links
**Actual Behaviour**

Please state here what is currently happening.
There are no facebook links
**Expected Behaviour**

State here what the feature should enable the user to do.
FB links to be added

**Would you like to work on the issue?**
Yeah sure!

### PR DESCRIPTION
**Pull request by samyakbvs**
#1532

### CODE REVIEW

**Comment by duttaditya18** [comment]
Hello!

**Comment by samyakbvs** [comment]
screen shot 2017-12-24 at 6 57 23 pm

**Comment by anantprsd5** [comment]
@samyakbvs I don't personally feel the need of a Facebook profile of a developer in the Readme file. @mohitmanuja What do you think?

**Comment by mohitmanuja** [comment]
I think we don't need it. So I am closing this issue.

**Pull request closed without merging**
