### PR TITLE
Fixes#126 : Added New Photobuttons for filter

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #126 

Changes:Added new photo buttons for snow and round corner filter
screenshot_2017-03-13-14-31-05-517_vn mbm phimp me
 

Screenshots for the change:

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
The text seems to not fit in the `ROUND CORNERS` button. Can you pad it well in the image? @madhavrathi

**Comment by madhavrathi** [comment]
@Abhi2424shek i will fix it.

**Comment by madhavrathi** [comment]
screenshot_2017-03-13-17-29-39-119_vn mbm phimp me
@Abhi2424shek  please review

**Comment by Abhi2424shek** [comment]
Fine.

**Pull request merged**
