### PR TITLE
Adding danger. (WIP)

### PR DESCRIPTION
**Pull request by CloudyPadmal**

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          2 Messages
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada:</td>
    </tr>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Thanks for the PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Abhi2424shek** [comment]
Yep danger is working.

**Comment by CloudyPadmal** [comment]
That looks awesome :metal:

**Comment by Abhi2424shek** [comment]
Now trying to generate the apk file...

**Comment by Abhi2424shek** [comment]
Waiting for travis

**Comment by Abhi2424shek** [comment]
@pa1pal it looks cool and good, I am updating the docs as well so that the developers can adjust with the changes.

**Comment by Abhi2424shek** [comment]
The last commit was a doc update so no worries. Merging.

**Pull request merged**
