### PR TITLE
Fix#1429 EditImage UI Updated

### LINKED ISSUE #1429: EditImageActivity UI Enhancement
**Actual Behaviour**

The UI of Edit Image should be updated.

**Expected Behaviour**

Enhancement of UI in Edit Image

**Would you like to work on the issue?**

Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fix #1429  UI Updated For Edit Image Activity

Changes: 
1.Set the buttons to the top
2.Preview Fragment is now hidden and is visible on clicking any of control fragment

Screenshots for the change: 
screenshot_2017-10-27-22-54-03

### CODE REVIEW

**Comment by codedsun** [comment]
@aditya98ak review this!

**Comment by sridharjajoo** [comment]
I think the previous UI was much better

**Comment by codedsun** [comment]
@sridharjajoo I have hidden the control panel, its not required to view witthout user action, I think.!
and the buttons is shifted to the parent view top which looks good according to me ! and I will be adding more features to it which will make it much better, but first instance of the UI is this.

@nikit19 @aditya98ak @mayank8318 What do u say?

**Comment by sridharjajoo** [comment]
Most of the photo editing apps around have the buttons at the bottom.

**Comment by codedsun** [comment]
@sridharjajoo no problem man ! Let other devs write their review if they also not like I will close the PR.

**Comment by mayank8318** [comment]
According to me this UI is much cleaner and clutter-less and serves the purpose with all the utility buttons on top. :+1:

**Comment by anantprsd5** [comment]
@codedsun I think the previous UI was better. I like these buttons to be at the bottom. @mohitmanuja What do you think?

**Comment by mohitmanuja** [comment]
@anantprsd5 Correct. So I am closing this PR.

**Pull request closed without merging**
