### PR TITLE
Single Image Editing page

### PR DESCRIPTION
**Pull request by Subhankar29**
Solved Issue: Redundant editing pages. #228

Changes: 
Previous behavior: After selecting a photo from the gallery and then selecting the editing option from the floating button CropImage activity opens which is different from that of the cropImage which we select from the camera activity. 

This PR removes the redundant activity and we have one single CropImage activity from both the options.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @Subhankar29 we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/Subhankar29/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pa1pal** [comment]
@Subhankar29 why it is showing previous commits.

**Comment by Subhankar29** [comment]
@pa1pal The latest commit is at the bottom, That I have to figure it out.

**Comment by pa1pal** [comment]
@Subhankar29 Properly rebase the code. Or close this and open new PR with relevant commits.

**Comment by amitiwary999** [comment]
@Subhankar29 are you working on this? I need this issue solved for improving my next issue and PR. So can I work on this?

**Comment by Subhankar29** [comment]
I did work on this. But it looks I need to rebase my code. Wait till tonight, I will rebase and send one more PR.

**Comment by amitiwary999** [comment]
@Subhankar29 any update?

**Pull request closed without merging**
