### PR TITLE
Changing title bar font

### PR DESCRIPTION
**Pull request by heysadboy**
Keeping the font of title bars in the app same everywhere

Solving issuse fossasia#192

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @heysadboy we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/heysadboy/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Abhi2424shek** [comment]
@anuja-k is on it. Please comment before working on an issue.

**Comment by heysadboy** [comment]
@Abhi2424shek Sorry. Should I close this?

**Comment by Abhi2424shek** [comment]
We can wait for @anuja-k and see what he thinks.

**Comment by mariobehling** [comment]
Thanks. Good job! Keep up your activity. Cheers.

**Pull request merged**
