### PR TITLE
changed flow and UI of editor

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #522 
Changes: 

- [x] Change the flow of editor
- [x] Add slider support for filters
- [x] Generate filter thumbnails
- [x] Add icons
- [x] Improve UI

screenshot_2017-06-09-17-19-14-971_vn mbm phimp me
screenshot_2017-06-09-17-19-46-365_vn mbm phimp me
screenshot_2017-06-09-17-20-00-881_vn mbm phimp me
screenshot_2017-06-09-17-20-12-991_vn mbm phimp me
screenshot_2017-06-09-17-20-22-229_vn mbm phimp me
screenshot_2017-06-09-17-20-28-510_vn mbm phimp me

### CODE REVIEW

**Comment by vinaysajjanapu** [comment]
Guys please check the flow of editor.(just the flow).

**Comment by anantprsd5** [comment]
@vinaysajjanapu Seems fine to me.

**Comment by the-dagger** [comment]
@vinaysajjanapu Could you also add some screenshots depicting the changes you've made?
Please follow the template provided for Pull Requests.

**Comment by vinaysajjanapu** [comment]
@the-dagger Added Screenshots.

@pa1pal It is not happening for me. You can see that in the screenshots added. In which device you are  testing this?

**Comment by Subhankar29** [comment]
@vinaysajjanapu Black spot displaying instead of sticker PNG. 
screen shot 2017-06-09 at 5 56 49 pm

**Comment by vinaysajjanapu** [comment]
@Subhankar29 that is not a png. That is a vector drawable made from svg. Can you please check its preview in activity_image_edit.xml whether that vector drawable is rendered properly.

**Comment by anantprsd5** [comment]
@vinaysajjanapu The app crashes on doing the following:
1. Crop the photo.
2. Go to filter.

Logs:
```
FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 32248
                                                                 java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:686)
                                                                     at vn.mbm.phimp.me.editor.editimage.fragment.RecyclerMenuFragment.getResizedBitmap(RecyclerMenuFragment.java:115)
                                                                     at vn.mbm.phimp.me.editor.editimage.fragment.RecyclerMenuFragment.access$200(RecyclerMenuFragment.java:28)
                                                                     at vn.mbm.phimp.me.editor.editimage.fragment.RecyclerMenuFragment$mRecyclerAdapter.onBindViewHolder(RecyclerMenuFragment.java:198)
                                                                     at vn.mbm.phimp.me.editor.editimage.fragment.RecyclerMenuFragment$mRecyclerAdapter.onBindViewHolder(RecyclerMenuFragment.java:143)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                     at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                     at android.view.View.measure(View.java:18991)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                     at android.view.View.measure(View.java:18991)
```

**Comment by mohitmanuja** [comment]
@vinaysajjanapu UI is impressive and the app is crashing on click on filter on cropped image.

**Comment by vinaysajjanapu** [comment]
@mohitmanuja thankyou.
Solved the crashes hopefully.
@pa1pal @anantprsd5 check again

**Comment by mohitmanuja** [comment]
@vinaysajjanapu Crash is resolved. 
Please check the stickers icon.

screenshot_2017-06-10-03-46-25-640_vn mbm phimp me

**Comment by vinaysajjanapu** [comment]
@mohitmanuja @Subhankar29 I changed the sticker icon. Check now.

**Pull request merged**
