### PR TITLE
Solved the redundant image editing page. 

### PR DESCRIPTION
**Pull request by Subhankar29**
Fixes issue #228. 

Changes: I have redirected the activity of the editing page. Now a single editing activity will be there if we choose a photo from the gallery or take a photo from the phone.  The editing activity is redirected to gallery3d.media.CropImage. We can further go and remove the activity image.CropImage which is of no use and is redundant. 

Screenshots for the change: 
screenshot_2017-05-07-06-47-13-736

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @Subhankar29 we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/Subhankar29/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pa1pal** [comment]
@Subhankar29 Please see the fail checks. Merging cause that.

**Comment by Subhankar29** [comment]
Ok. On it.

**Comment by Subhankar29** [comment]
I updated my tavis.yml folder. It showed the successful message at travis CI website. Please have a check.

**Comment by pa1pal** [comment]
@Subhankar29 There is no problem with the `travis.yml`. A quick fix would be if you reset hard some previous commits and rebase it with development branch.

**Comment by pa1pal** [comment]
@Subhankar29 not large changes. So can you  open a new PR for the same? Create a new branch from the updated code.

**Comment by Subhankar29** [comment]
Yeah, doing that.

**Pull request closed without merging**
