### PR TITLE
fix: Dialog appearance improved.

### LINKED ISSUE #2672: Select font dialog issue.
**Describe the bug**
Select font dialog issue while editing image does not look good.

**To Reproduce**
1. Go to edit image.
2. Go to write.
3. Select Font. The dialog whch pops up has no padding in the text. The heading of the dialog also does not look like it does in other dialogs.

**Expected behavior**
The look of the dialog should be improved.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 plus|
|Android Version|Android 9    |

**Would you like to work on the issue?**

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2672 

Changes: Font dialog now appears better than it was.

Screenshots of the change: 

screencap

### CODE REVIEW

**Comment by abishekvashok** [comment]
I would rather implement one similar to Snapseed without a dialog.

**Comment by yashk2000** [comment]
@abishekvashok you mean a horizontal scroll view, as used to choose colors presently?

**Comment by abishekvashok** [comment]
Yes

**Comment by yashk2000** [comment]
Ok. Working on it.

**Comment by mariobehling** [comment]
Ok, I am merging this as WIP. Let's follow up on this.

**Pull request merged**
