### PR TITLE
Fixes #125 Add option to check Image details

### LINKED ISSUE #125: Add an option to check details of an image
**Actual Behaviour**

There is no option to display particular details like time, resolution etc. of the images.

**Expected Behaviour**

There should be an info button to check the basic details of the images, something like the below screen shot.

**Screenshots of the issue**

photo_2017-03-12_21-42-20

**Would you like to work on the issue?**

Yes. Would love to.

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #125 Add option to check Image details

Changes: Added an info button which on being clicked displays the basic image information.

Screenshots for the change: 
photo_2017-03-16_20-59-30

On small screens: 
photo_2017-03-17_00-18-54

### CODE REVIEW

**Comment by heysadboy** [comment]
I think you should just put a blue color text instead of wider button. You can use an AlertDialog instead of making this from scratch.

**Comment by anantprsd5** [comment]
@heysadboy I think the wider button looks good, thats why I did like that.

**Comment by anantprsd5** [comment]
@pa1pal Made the required changes. Is it good now?

**Comment by heysadboy** [comment]
@anantprsd5 Oki

**Pull request merged**
