### PR TITLE
Fix #1280 add option for slideshow

### LINKED ISSUE #1280: No option for slideshow
**Actual Behaviour**

Currently there is no option for slideshow.

**Expected Behaviour**

There should be an option for slideshow so that the users can view photos one after the other. 

**Steps to reproduce it**

Open the singleMediaActivity and you will see that there is no option for slideshow.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by nikit19**
Fix #1280 

Changes:added an option for slideshow

Screenshots for the change: 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by nikit19** [comment]
@mohitmanuja @anantprsd5 please review

**Comment by anantprsd5** [comment]
@nikit19 It would be good to hide the toolbars while displaying images using slideshow. Show the toolbars when user taps on the screen

**Comment by nikit19** [comment]
@anantprsd5  done with the requested changes.

ezgif com-video-to-gif 6

**Comment by anantprsd5** [comment]
@nikit19 Resolve conflicts

**Comment by nikit19** [comment]
@anantprsd5  conflicts resolved

**Comment by mohitmanuja** [comment]
@nikit19 please resolve conflicts.

**Comment by nikit19** [comment]
@mohitmanuja conflicts are resolved

**Pull request merged**
