### PR TITLE
Fixed the Bottom Nav Sliding Direction Issue

### LINKED ISSUE #2923: Bottom menu bar "move in effect" not from expected direction
If a user clicks on the left "camera" icon it would be expected that the cam function screen moves in from the left as well. If the user is on the "accounts screen" and clicks "Gallery" it would be expected that the "Gallery screen" moves in from the left. Instead it moves in from the right.

Please check and correct this. Screens should be moving in from the expected direction according to the bottom buttons.

### PR DESCRIPTION
**Pull request by satyajiit**
Fixed #2923 

Changes: Added a global variable to MyApplication Class.
And applied transition based on logic/conditions to each of the three activities.
NavItem starts from zero to two.
Since we have three NavItems.
Added four new anim xml files and deleted the old two.

This PR also contains fix for #2894 

GIF :
gif

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please resolve conflicts.

**Comment by satyajiit** [comment]
Done . Sorry for that conflict 🙂

**Comment by codedsun** [comment]
Please review my comment, PR contains unnecessary code yet.

**Comment by satyajiit** [comment]
@codedsun When building with SDK 29 ,
on Android 10 , 
it gives error on run.

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.phimpme/org.fossasia.phimpme.gallery.activities.SplashScreen}: android.view.InflateException: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Binary XML file line #17 in org.fossasia.phimpme:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
```

But compiling with SDK 28 resolves the issue.
Because of some outdated libraries. 

No crash occurs when run with versions < android 10 .

**Comment by codedsun** [comment]
@satyajiit Then what about the devices running on android 10?

**Comment by satyajiit** [comment]
@codedsun I am testing the App on Android 10.
The exact issue with build.gradle changes :
 compileSdkVersion 29
buildToolsVersion "29.0.2"
targetSdkVersion 29

Gradle build will succeed but if test the App on Android 10 ,
I am using OnePlus7 .
Just in the SplashScreen the app will crash.


But If i build the project with Sdk28 and buildTools 28 ,
All works fine.

**Comment by satyajiit** [comment]
I am closing this PR ,
And making another with fix to only #2923 .
Thank You @codedsun

**Pull request closed without merging**
