### PR TITLE
fixes issue #501 changes in camera

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #501 

Changes: Removed unused features from camera and changed UI.
                Removed video related functions completely.
If the UI is not satisfactory we can change it in new PR.
Screenshots for the change: 
screenshot_2017-06-01-01-23-34-187_vn mbm phimp me

### CODE REVIEW

**Comment by anantprsd5** [comment]
@vinaysajjanapu Please check the StorageUtils.java file, unused options related to videos are there. It will be great if you update the Screenshot of the camera in this PR itself.

**Comment by vinaysajjanapu** [comment]
@anantprsd5 any suggestions on the UI?

**Comment by anantprsd5** [comment]
I find it nice. Clean and simple.

**Comment by mohitmanuja** [comment]
Yes, Camera UI is now clean.

**Comment by Subhankar29** [comment]
Looks Good! But I think we should apply the standard camera onClick button(the white one), that looks better.

**Comment by pa1pal** [comment]
Yes I think same @Subhankar29 .
Rest camera ui looks good now.

**Comment by vinaysajjanapu** [comment]
screenshot_2017-06-01-19-23-01-391_vn mbm phimp me

**Pull request merged**
