### PR TITLE
Removed hard Coded Dimensions from camera layout

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #163 (Improvement) 

Changes: Removed hard coded dimensions from camera layout and added them pro-grammatically.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @madhavrathi we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/madhavrathi/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by madhavrathi** [comment]
@Abhi2424shek  Please Review

**Comment by pa1pal** [comment]
Edit the description and title of the PR.

**Comment by madhavrathi** [comment]
@pa1pal  I just checked that the file was having indentations in both tabs and space(in different chunks of code), so i made it uniform by intending by spaces.

**Comment by pa1pal** [comment]
@madhavrathi The indentation of tabs and spaces is pretty clear from you PR. As it is showing relevant addition and deletion. 
But why it is showing complete addition and deletion from line `216` to `626`?
Don't you think it should only show addition of your code and improving of indentation?

**Comment by madhavrathi** [comment]
@pa1pal i was actually wondering the same. i still don't know why the diff is showing additions like that. so what do you suggest i should do about this .

**Comment by pa1pal** [comment]
@madhavrathi reset the changes for only one file and again edit it.
`git reset -- <FILE_NAME> HEAD~<NUMBER>`

**Comment by madhavrathi** [comment]
@pa1pal @Abhi2424shek  I guess it's resolves now. Please Review.

**Pull request merged**
