### PR TITLE
Established the basic layout of the Image Sharing Activity and basic image sharing

### PR DESCRIPTION
**Pull request by Subhankar29**
Fixes issue ##499

Changes: Made the Image Sharing Activity. Successfully triggering image sharing through the inbuilt application. Other sharing options are yet to be established. Currently only sharing through the inbuilt application is established. 

Screenshots for the change: 
screenshot_2017-05-31-00-16-13-624

### CODE REVIEW

**Comment by Subhankar29** [comment]
@pa1pal @mohitmanuja @vinaysajjanapu @anantprsd5 please review it.

**Comment by mariobehling** [comment]
@Subhankar29 Why should people review Work in Progress?

**Comment by mohitmanuja** [comment]
@Subhankar29 Please update your fork and then send PR or do work in the new branch. Because your PR contains so many old commits.

**Comment by Subhankar29** [comment]
@mariobehling I thought they can give me the feedback for the work done till date. Ok, will ask for the review after the work is done.

**Comment by Subhankar29** [comment]
@pa1pal I referred this site for the icon: https://www.iconfinder.com/icons/1632505/circle_drupal_round_icon_icon#size=128

**Comment by pa1pal** [comment]
@Subhankar29 okay. It can be used as per license.

**Pull request closed without merging**
