### PR TITLE
Closes #335 : Touch space according to Material Guidelines

### LINKED ISSUE #335: Not enough touch space for Camera feature buttons
**Actual Behaviour**

The existing _Switch Camera_, _Flash_ and _Grid_ buttons are stuffed and the space is inadequate! 

**Expected Behaviour**

According to Material Design Guidelines, there has to be a touch space like 48dp x 48dp for interactions

**Steps to reproduce it**

1. Open app
2. Go to _Camera_ and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

device-2017-04-12-164033

**Would you like to work on the issue?**

Yes :)

### PR DESCRIPTION
**Pull request by CloudyPadmal**
Fixes issue #335 

Changes:
- Replaced existing _Camera Switch_ icon with Camera Switch Material Icon
- Added 48dp touch space to 24dp icons

Screenshots for the change: 
device-2017-04-13-081636

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @CloudyPadmal we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/CloudyPadmal/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Abhi2424shek** [comment]
Looks good, but like other apps, can you place the more useful and used ones on to the bottom and the other ones to the top corners?

**Comment by CloudyPadmal** [comment]
Hello @Abhi2424shek ! Do you mean placing the three icons on two bottom corners and top corners? :)

**Comment by Abhi2424shek** [comment]
Yes, can you do it here or shall I open another issue for it?

**Comment by CloudyPadmal** [comment]
I can do it here! I'll send a PR soon! :)

**Comment by CloudyPadmal** [comment]
Hello @Abhi2424shek ! Is this okay? :)

device-2017-04-13-113516

**Comment by Abhi2424shek** [comment]
Thanks

**Comment by CloudyPadmal** [comment]
Thank you Abhishek!! :blush:

**Pull request merged**
