### PR TITLE
Fixes #194 : Add option to select all images in the image selector

### LINKED ISSUE #194: Add option to select all images in the image selector
**Actual Behaviour**

There is no option to select all images in any image selector.

**Expected Behaviour**

There should be option on the toolbar on long pressing an image to select all the images at once.

**Screenshots of the issue**

screenshot_2017-03-20-00-16-40-759_vn mbm phimp me

**Would you like to work on the issue?**

Yes, I would like to work on it.

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes issue #194 

Screenshots for the change: 

screenshot_2017-03-28-00-01-26-720_vn mbm phimp me
screenshot_2017-03-28-00-01-18-032_vn mbm phimp me

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @rohanagarwal94 we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/rohanagarwal94/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by rohanagarwal94** [comment]
@pa1pal made the necessary changes. Please review.

**Comment by pa1pal** [comment]
It keeps increasing the selected images counter, if I continuously clicks select all button.

**Comment by rohanagarwal94** [comment]
@pa1pal closing this PR. Please refer #270 for the complete changes and review it.

**Pull request closed without merging**
