### PR TITLE
Fixes Image clicks on exposure bracketing and Burst modes

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #577 PhotoActivity opens more than once on clicking image on Exposure bracketing mode.

Changes:
 1. Added conditions for Exposure bracketing and Burst modes.
 2. Removed unused imports from Preview.java file

### CODE REVIEW

**Comment by mohitmanuja** [comment]
@anantprsd5 In some cases it is not working properly. i.e select burst mode 3x now it will open single image activity on the first pic.

**Comment by pa1pal** [comment]
I only check the exposure feature.

**Comment by anantprsd5** [comment]
@pa1pal I also added conditions for burst mode in this PR itself. @mohitmanuja Yes, I have reproduced the issue. Looking into it now.

**Comment by anantprsd5** [comment]
Done with all the changes. Please review.

**Pull request merged**
