### PR TITLE
Fix #1787 preview filter image size is small

### LINKED ISSUE #1787: preview filter image size is small
**Actual Behaviour**

Preview filtered image in bottom bar is so small in size.

**Expected Behaviour**

This size should be larger so that user can view pre-filter image.

**Steps to reproduce it**

* Change the preview filter image icon size
* Dynamically changing this size of icon for non filter(like enhance,transform)

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by ashley8jain**
Fixed #1787 

Changes: 
* Change the preview filter image icon size
* Dynamically changing this size of icon for non filter(like enhance,transform) layout

Screenshots for the change: 
screencast

### CODE REVIEW

**Comment by ashley8jain** [comment]
@anantprsd5 @isuruAb please review

**Comment by codedsun** [comment]
I think the main aim was that the size of the bottom toolbar remains the same ! let other devs check this out. @mayank8318 @sauravvishal8797 @nikit19

**Comment by ashley8jain** [comment]
But user cant see the preview small image clearly in current size, 
so preview filter image should be above size as same as Instagram filter app.

**Comment by ashley8jain** [comment]
@isuruAb Kindly review this please

**Comment by abishekvashok** [comment]
Waiting for views @isruArb @anantprsd5

**Pull request merged**
