### PR TITLE
#1731 Fixed-Search button in actionbar

### LINKED ISSUE #1731: Search button can be shown in actionbar always instead of sort button
Actual Behaviour
Sorting button is placed instead of search button,now users wont get the idea if they have the option to  search the image or not.

Expected Behaviour
Search button should be placed instead of sorting button.
.

Steps to reproduce it

Open the "Camera" in the bottom navigation bar of the app .

### PR DESCRIPTION
**Pull request by Ananthusubramanian**
Fixed #1731  Search button in actionbar

Changes:Now the search button is displayed in the actionbar with an icon

Screenshots for the change:

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian Could be better if you show the search icon before the all photos icon in the toolbar.

**Comment by Ananthusubramanian** [comment]
@sauravvishal8797  I changed the positions ,now its look nice

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian Please attach the screenshot for the change in the commit.

**Comment by Ananthusubramanian** [comment]
@sauravvishal8797  I changed the order of items so that it comes first

**Comment by Ananthusubramanian** [comment]
@sauravvishal8797  This is the screenshot of the commit
screenshot_2018-01-25-19-10-01-496_org fossasia phimpme

**Pull request merged**
