### PR TITLE
chore: Changes in travis.yml

### PR DESCRIPTION
**Pull request by yashk2000**
Changes: Made changes in the travis.yml file. Now instead of 3 parallel jobs, 2 jobs are run in series. Time taken is approximately the same.

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok please review.

**Comment by iamareebjamal** [comment]
Also, we have 3 tests in integration tests for Android. That's insanely low amount of tests to waste 20 minutes of build time. There are also explicit sleeps of 10 seconds or so.

Some of the tests are so basic that they test that if I click on a tab, it goes to that tab. This is tested by Android framework team, why are we testing it? We should check our own logic. 

Please find last 5 PRs in which these tests failed so that we can evaluate their importance. Then, we'll either remove them or improve them by removing sleep statements and converting them to RoboElectric tests so that they can run on JVM without AVD

**Comment by yashk2000** [comment]
https://github.com/fossasia/phimpme-android/pull/2571
https://github.com/fossasia/phimpme-android/pull/2524
https://github.com/fossasia/phimpme-android/pull/2426
https://github.com/fossasia/phimpme-android/pull/2414
https://github.com/fossasia/phimpme-android/pull/2372

@iamareebjamal last 5 prs in which tests failed.

**Comment by yashk2000** [comment]
@iamareebjamal should I make any more changes to the travis script?

**Comment by iamareebjamal** [comment]
I'll analyse these PRs and open an issue if needed

**Comment by iamareebjamal** [comment]
@yashk2000 We need PRs where only COMPONENT=CONNECTED_TEST is failing. All these PRs have build failing. We need to see how important connected tests are for the project

**Comment by yashk2000** [comment]
@iamareebjamal ok. I'll search for prs in which CONNECTED_TEST is failing.

**Pull request merged**
