### PR TITLE
Integrating twitter in account manager

### PR DESCRIPTION
**Pull request by pa1pal**
Fixes issue #526 

Changes: 

- [x] Adding twitter sign in functionality in account manager using Twitter Kit (api) 
- [x] adding Realm database to save account data such as username, email and accesstoken

TODO: signout feature in main accounts list.

### CODE REVIEW

**Comment by anantprsd5** [comment]
@pa1pal Where can the user disconnect the account if he wants to. There is no option to sign out.

**Comment by pa1pal** [comment]
@anantprsd5 Yes this a case which I will add in the main account list. A cross icon to sign out. 
This is a big feature, so don't want to add everything in a single PR. We will do it subsequently. 

To verify everything get saved, you can attach debugger on `AccountPickerFragment` to see the data.

**Comment by mariobehling** [comment]
Please also resolve conflicts.

**Comment by pa1pal** [comment]
@mariobehling done

**Pull request merged**
