### PR TITLE
fix: Prevented other dialogs in edit activity from being dismissed on orientation change.

### LINKED ISSUE #2787: Dialogs disappearing on orientation change.
**Describe the bug**
There are some dialogs which disappear on dialog change.

**Expected behavior**
The dialogs should not be dismissed on orientation change.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2787 

Changes: Prevented dialogs n edit image activity from being dismissed when orientation is changed.

### CODE REVIEW

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @abishekvashok @mariobehling please review.

**Comment by yashk2000** [comment]
@adityastic @iamareebjamal @abishekvashok @mariobehling please review.

**Comment by yashk2000** [comment]
@iamareebjamal please review.

**Comment by yashk2000** [comment]
@iamareebjamal please review.

**Comment by yashk2000** [comment]
@mariobehling @iamareebjamal please review.

**Comment by abishekvashok** [comment]
Thanks

**Pull request merged**
