### PR TITLE
Share Image to Twitter.

### PR DESCRIPTION
**Pull request by Subhankar29**
Fixes issue #585 

Changes: Added sharing Image option to Twitter. 

Screenshots for the change: 
screenshot_2017-06-17-02-50-14-437

### CODE REVIEW

**Comment by the-dagger** [comment]
@shubh24 Please squash the commits manually.
Since we are not squashing the commits during merge, you need to squash them at your end.

**Comment by mohitmanuja** [comment]
@Subhankar29 It is not working. The only text is displaying and on click on the tweet button, it is not working.

whatsapp image 2017-06-18 at 1 23 52 am

whatsapp image 2017-06-18 at 1 23 55 am


The second thing is on sign in it is showing "the full name" instead of my name.

whatsapp image 2017-06-18 at 1 26 18 am

**Comment by Subhankar29** [comment]
@mohitmanuja Pawan is handling Twitter sign in. I will inform him.
And Yes this is the issue I was talking about, Pawan's one more PR is yet to be approved from where the Twitter account token can be accessed, that will fix the issue I guess.

**Comment by Subhankar29** [comment]
@pa1pal @mohitmanuja @vinaysajjanapu @anantprsd5 @the-dagger I have made the changes, please review it.

**Pull request merged**
