### PR TITLE
Added flickr android api

### LINKED ISSUE #741: Adding flickr api and UI for flickr share
**Actual Behaviour**

There is no such feature in the app currently

**Expected Behaviour**

Ability to upload image to Flickr

**Steps to reproduce it**

Select Image -> Share

**Would you like to work on the issue?**

yes.

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fix #741 

Changes: 

- [x]  Added flickr android API
- [x]  Added flickr element in accounts list in account activity
- [x] Removed redundant arraylist and refactored the code in account activity.
- [x] Changed bottomnavigationbar color by changing theme in manifest.

### CODE REVIEW

**Comment by anantprsd5** [comment]
@vinaysajjanapu Please resolve conflicts.

**Comment by mariobehling** [comment]
@vinaysajjanapu You are violating best practices merging your own PRs. Don't do this!

**Comment by vinaysajjanapu** [comment]
@mariobehling It received 3 approved reviews from members with write access. So, it can be self merged. We are following this from the beginning.

**Comment by mariobehling** [comment]
@vinaysajjanapu Yes, I understand. In this case the third reviewer should merge it. It is not a good practice if a dev merges his/her own PRs.

**Pull request merged**
