### PR TITLE
Fix #1746 - Add a highlight(icon) on the favourite image.

### LINKED ISSUE #1746: Add a highlight(icon) on the favourite image
**Actual Behaviour**

There is no indication that an image is favourite.

**Expected Behaviour**

There should be some mark on the image.

**Steps to reproduce it**

Add any image to favourites.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixed #1746 

Changes: Add a star icon for favourite images.

Screenshots for the change: 
image

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@mayank8318 Maybe it'll look better if the highlight icon is set to the lower right corner, just an opinion.

**Comment by mayank8318** [comment]
@sauravvishal8797 Most apps have it in the top right corner, so it put it there. Lets see what others have to say?
@nikit19 @codedsun @mohitmanuja @isuruAb @anantprsd5

**Comment by codedsun** [comment]
Looks great 👍

**Comment by ashley8jain** [comment]
@mayank8318 this star is not visible in some yellow pics, so add the white borderline to star symbol

**Comment by mayank8318** [comment]
@ashley8jain Please check now :)

**Comment by isuruAb** [comment]
please resolve conflicts

**Comment by mayank8318** [comment]
Updated screenshots :
image

**Comment by isuruAb** [comment]
thank you @mayank8318

**Pull request merged**
