### PR TITLE
Added Image Filters

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #440 

Changes: 
- [x] Histogram Equalization
- [x] Threshold
- [x] Grain

### CODE REVIEW

**Comment by vinaysajjanapu** [comment]
@pa1pal @mohitmanuja @anantprsd5 @Subhankar24 If anyone one of you is familiar with image processing please check this PR. I am facing trouble in implementing skin smoothening.

**Comment by anantprsd5** [comment]
@vinaysajjanapu I found this https://github.com/AmniX/HighPassSkinSmoothing-Android open source project for skin smoothening. It might be helpful.

**Comment by vinaysajjanapu** [comment]
@the-dagger Please check this codacy error. 
The jni funtions gets called from java with some other name (not exactly the same because they are native functions). 
Codacy is showing "unused functions" error for that.
It is also showing error for scope of variable which is correct.

**Comment by vinaysajjanapu** [comment]
There is some problem with skin smoothening, Its execution time is very high. I'll optimize and open another PR for it later. Please merge these three filters.

PS: histogram equalization works better with dark images or foggy images. (not for portraits)

**Pull request merged**
