### PR TITLE
Fixes #296 Image cropping doesn't save the cropped image

### LINKED ISSUE #296: Image cropping doesn't save the cropped image
**Actual Behaviour**

When I try to crop an image without applying any filter, it doesn't save the cropped image.

**Expected Behaviour**

When an image is being cropped, it should be saved when we click on _OK_ button

**Steps to reproduce it**

1. Open app
2. Select an image and open the full image view
3. Click on the FAB and select _Edit_ button
4. Crop the image **without** applying any filter
5. Click _OK_
6. Go to _Gallery_ and observe

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

I've assigned myself one issue. So this one is open to anyone :)

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #296
Changes: There were unnecessary flags and checks for saving the picture. Removed it. It fixed the issue.

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @vinaysajjanapu we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/vinaysajjanapu/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mariobehling** [comment]
Thank you! With so many pr resolve conflicts happen. Please help to resolve them. Cheers.

**Comment by vinaysajjanapu** [comment]
Help required in resolving conflicts...
The indentation of the file had been changed. So it is getting very difficult for me to indent to match that file. I tried indenting, that didn't work. I tried copying whole code from main repo and made changes in it again. That also didn't work. It even resulted in more complex conflicts which I can't even view in browser. 
PS: This file can be replaced with my version of file as both files have same code except indentation and the changes that I made in this branch.

**Comment by pa1pal** [comment]
@vinaysajjanapu why it didn't work when you make changes again. Rebase your branch to current main development branch and make changes there.

**Comment by vinaysajjanapu** [comment]
Finally it is done.. Conflicts resolved.

**Pull request merged**
