### PR TITLE
LFActivityMain.java: Implements Butterknife

### LINKED ISSUE #1500: Implement Butterknife in `LFMainActivity`
**Actual Behaviour**

Butterknife is not implemented in `LFMainActivity`

**Expected Behaviour**

It can be implemented.

**Would you like to work on the issue?**

Can be claimed by any GCI student

### PR DESCRIPTION
**Pull request by abishekvashok**
Implements Butterknife in LFActivityMain.java and binds all views inside
it.

Changes:
Implements Butterknife in LFActivityMain.java It was not implemented
earlier.

Fixes #1500

### CODE REVIEW

**Comment by abishekvashok** [comment]
@mayank8318 done it in the latest commit. LEt's wait for Travis.

**Comment by abishekvashok** [comment]
@mayank8318 pls review now, Travis runs fine, tested the app and it works fine.

**Comment by anantprsd5** [comment]
@abishekvashok Are you doing this as a part of GCI?

**Comment by abishekvashok** [comment]
@anantprsd5 yes

**Comment by anantprsd5** [comment]
Did you claim the task from the gci dashboard?

**Comment by abishekvashok** [comment]
@anantprsd5 as I can see, I have a current task, which should be approved, as soon aas it is approved, I will take on the phimpme task :)

**Comment by abishekvashok** [comment]
@anantprsd5 thanks;
Link to my task: https://codein.withgoogle.com/dashboard/task-instances/4804307457146880/

**Pull request merged**
