### PR TITLE
fix: switch compat color using Styles

### LINKED ISSUE #904: No background tint in Account Manager Switch compat
**Actual Behaviour**

The switch in the account manager shows a grey circular button only in case of switch off action. There is no background tint

**Expected Behaviour**

Adding a grey background tint.

**Steps to reproduce it**

Open --> Account manger 

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by pa1pal**
Fix #904 

Changes: Added a new style and applied it on `SwitchCompat`

Screenshot
screen shot 2017-08-01 at 7 31 01 pm

### CODE REVIEW

**Comment by pa1pal** [comment]
@anantprsd5 @mohitmanuja @vinaysajjanapu @Subhankar29 is this working with your device?

**Comment by anantprsd5** [comment]
photo6336951742914209724

@pa1pal Not working.

**Comment by pa1pal** [comment]
@anantprsd5  I'm not getting, why styles not applying to it.

**Comment by mohitmanuja** [comment]
@pa1pal Theme attribute doesn't work in RecyclerView on pre-material APIs.
 I would suggest set colour programmatically.

https://stackoverflow.com/questions/32499691/change-colorcontrolactivated-color-programmically

**Pull request merged**
