### PR TITLE
Fixed #1782 Translucent status bar now  sets in security and exculded item activity.

### LINKED ISSUE #1782: Translucent status bar is not set in security and exculded item activity.
**Actual Behaviour**

Even if the toggle button for translucent status bar is on, a darker primary color is not applied to the notification bar for security and excluded item activity.

**Expected Behaviour**
A darker primary color should be applied to the notification bar for security and excluded item activity.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by raj10071997**
Fixed #1782

Changes: The status bar in security and excluded item activity is now set to a darker primary theme if the toggle button is on.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Closing as left stalked

**Comment by raj10071997** [comment]
@abishekvashok  I forgot about this PR but it is valid PR about the issue. Can you please reopen it and tell me changes that are needed to be done?

**Comment by abishekvashok** [comment]
Done

**Comment by abishekvashok** [comment]
Please resolve build errors encountered.

**Comment by raj10071997** [comment]
@abishekvashok  All the tests has been passed.Please review this PR again.

**Pull request merged**
