### PR TITLE
Closes issue #349 Camera preview is distorted [WIP]

### PR DESCRIPTION
**Pull request by vinaysajjanapu**
Fixes issue #349 

Changes: 
- Changed logic for selecting supported preview size.
- Changed the preview size to match the optimal preview size
- removed unnecessary code

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @vinaysajjanapu we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/vinaysajjanapu/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by vinaysajjanapu** [comment]
Any suggestions for the new UI?
screenshot_20170416-174755

**Comment by vinaysajjanapu** [comment]
@pa1pal I am not facing this error. I have checked the code and changed the part which I feel might be causing this issue. Can you please check this in your device

**Comment by pa1pal** [comment]
@vinaysajjanapu But is happening in my device. It is not taking full width

**Comment by vinaysajjanapu** [comment]
@pa1pal have you checked my recent commit?
Today I checked in my friend's phone. It also has the same issue as yours but my yesterday's changes fixed that issue.

**Comment by pa1pal** [comment]
@vinaysajjanapu Yes checked on recent commit

**Comment by Abhi2424shek** [comment]
Hey, @vinaysajjanapu please do only one issue per PR, please don't change the layout unless necessary, it would be better if you could straight forward solve the issue and nothing else in a single PR. :)

**Comment by vinaysajjanapu** [comment]
@pa1pal can you check this on your phone once?

**Comment by pa1pal** [comment]
same issue

**Comment by vinaysajjanapu** [comment]
@pa1pal can you please check what's wrong with this. Because I checked it in almost all the phones which I have access to and it worked fine in each and every one. So, I can't even understand what going wrong with this.

**Comment by pa1pal** [comment]
The onlayout function calls 6 six times and changed the value of width and height.

**Comment by vinaysajjanapu** [comment]
that is a problem, I agree.  I don't think that is affecting the final preview size of the camera

**Comment by pa1pal** [comment]
@vinaysajjanapu it's affecting. I tested in other devices as well.
I am merging this now. And solve the issue in my seperate PR.

**Comment by vinaysajjanapu** [comment]
That was very helpful. Thankyou.

**Pull request merged**
