### PR TITLE
Imagedetails are shown properly in the landscape mode

### LINKED ISSUE #1602: Bug in landscape mode of Description of image
**Actual Behaviour**
When the phone is rotated and description of an image is seen , the details are cutoff i.e there should be a scroll view so that all the details can be seen.

**Steps to reproduce it**
Open any image and in the bottom navigation bar , select the description/details option.
Rotate the phone to view in landscape mode.

**Screenshots of the issue**
rsz_potrtait

rsz_landscape

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by batbrain7**
Fixed #1602 

Changes: Added the landscape mode files so that all the details of the image are shown.
Not used the scrollview as in this way all the files are visible right on the screen.

Screenshots for the change: 
screenshot_20180128-154352

### CODE REVIEW

**Comment by batbrain7** [comment]
@sridharjajoo @codedsun @isuruAb @anantprsd5 
Please review!

**Comment by isuruAb** [comment]
@batbrain7  please check the travis failure

**Comment by batbrain7** [comment]
@isuruAb working on it

**Comment by batbrain7** [comment]
@isuruAb all the checks have now passed

**Pull request merged**
