### PR TITLE
[WIP] chore: Update build gradle version to 3.4.1

### PR DESCRIPTION
**Pull request by yashk2000**
Changes: Updated build gradle version to 3.4.1.

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal I've made no changes to the travis script in this one. Here this error occurs:
`A problem occurred configuring project ':app'.
Parameter specified as non-null is null: method com.android.build.gradle.internal.cxx.configure.JsonGenerationVariantConfiguration.<init>, parameter ndkVersion`

**Comment by iamareebjamal** [comment]
Update NDK as well

**Comment by yashk2000** [comment]
@iamareebjamal updated. In this case, the NDK does not get downloaded. 
I tried this too :
` wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip`

  `- unzip android-ndk-r16b-linux-x86_64.zip -d $HOME`

  `- export ANDROID_NDK_HOME=$HOME/android-ndk-r16b`

` - export PATH=$PATH:$ANDROID_NDK_HOME`

On doing this, there is a problem with building the AVD.

**Comment by iamareebjamal** [comment]
Because it's giving 404

**Comment by iamareebjamal** [comment]
https://github.com/googlesamples/android-ndk/blob/master/.travis.yml

**Comment by iamareebjamal** [comment]
https://gitlab.com/ecoin_exchange/geth-drag/commit/c971ab617d57f614c1d84ad44efdf662cee00758

**Comment by iamareebjamal** [comment]
You just downloaded the zip. Who'll extract it. Please copy carefully as bit to bit

**Comment by ucone** [comment]
download correct open cv version
i follow your steps if errors happen i have to delete  .externalNativeBuild and build  but   .externalNativeBuild and build appear again and i have 4 error relating style
Error:(195, 5) error: invalid parent reference 'style/Widget.AppCompat.Button.ButtonBar.AlertDialog'.
Error:(6154) invalid parent reference 'style/Widget.AppCompat.Button.ButtonBar.AlertDialog'.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:mergeDebugResources'.

Error: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by yashk2000** [comment]
@ucone thanks for the suggestion. @iamareebjamal do we need to update the version of openCV being used? Currently, we are using 2.4.13.3

**Comment by iamareebjamal** [comment]
Maybe

**Comment by yashk2000** [comment]
@iamareebjamal I searched for the error in the Travis build. It is because the c/c++ files are currently being tested by gcc/g++ while we need to use clang as gcc is now depreciated in the NDK we are using. So maybe updating the openCV library will. I'll try doing that.

**Comment by yashk2000** [comment]
@iamareebjamal I used a newer version of openCV which has 64 bit libraries. It's building successfully in android studio and running fine on the device. 
I tried it on this branch: 
https://github.com/yashk2000/phimpme-android/tree/trial_ndk_toolchain
But the build is still showing one error:
`Android NDK: ERROR:/home/travis/build/yashk2000/phimpme-android/app/src/main/jni/Android.mk:opencv_shape: LOCAL_SRC_FILES points to a missing file    
  Android NDK: Check that /home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_shape.a exists  or that its path is correct   
`
Here is the travis build for this:
https://travis-ci.org/yashk2000/phimpme-android/builds/541080226
 
Please help me resolve this error. I think after this is resolved, the build should pass.

**Comment by iamareebjamal** [comment]
There's no jniLibs folder. Maybe you forgot to copy it

Please `Check that /home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_shape.a exists or that its path is correct `

**Comment by yashk2000** [comment]
@iamareebjamal the folder jniLibs isn't supposed to be inside jni. It is a separate folder inside `app/src/main`

**Comment by yashk2000** [comment]
I am not able to figure out where during the build the command is executed to find that particular file. If I can find the location, I will change it manually.

**Comment by abishekvashok** [comment]
I guess it's ndk and opencv conflicting

**Comment by yashk2000** [comment]
@abishekvashok the openCV version change is needed as we need to introduce 64-bit libraries in the app. That is required by google and has to be done before August. 
Which version of ndk do you recommend that I use? I am using version r16b in my local machine and that is working fine.

**Comment by iamareebjamal** [comment]
the folder jniLibs isn't supposed to be inside jni. It is a separate folder inside app/src/main

Then change the path in OpenCV.mk

**Comment by iamareebjamal** [comment]
https://github.com/yashk2000/phimpme-android/blob/trial_ndk_toolchain/app/src/main/jni/OpenCV.mk#L17

**Comment by yashk2000** [comment]
@iamareebjamal that is not an error. The copy_openCV.sh script copies libs from the openCV to jniLibs folder in main after creating it.
I found one of the error though. The download openCV script is still downloading v2.4.13.3. I have to change to 3.2.0, that should solve some of the errors.

**Comment by iamareebjamal** [comment]
`that is not an error. The copy_openCV.sh script copies libs from the openCV to jniLibs folder in main after creating it.`

Not sure how is it not an error when it literally says `LOCAL_SRC_FILES points to a missing file Android NDK: Check that /home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_shape.a exists or that its path is correct`

Reason may be outdated OpenCV version but the issue is that it can't find the file in the directory

**Comment by yashk2000** [comment]
Yes sir, that shouldn't happen. But I have built the app several times, and there is not supposed to be `jniLibs` folder inside the `jni` folder. 
I have pushed changes to opencv_download.sh script in my branch. I'll inform you about the build status as soon as it ends.

**Comment by iamareebjamal** [comment]
`/home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_shape.a` == `/home/travis/build/yashk2000/phimpme-android/app/src/main/jniLibs/armeabi-v7a/libopencv_shape.a`


.. means one directory back

**Comment by yashk2000** [comment]
@iamareebjamal that error is because the old version of openCV doesn't have that folder.

**Comment by yashk2000** [comment]
Let's see if updating the openCV download version solves any problems.

**Comment by yashk2000** [comment]
The build is still failing with the same error.
https://travis-ci.org/yashk2000/phimpme-android/builds/541332114

**Comment by iamareebjamal** [comment]
```
unzip:  cannot find or open opencv-3.2.0-android-sdk.zip, opencv-3.2.0-android-sdk.zip.zip or opencv-3.2.0-android-sdk.zip.ZIP.
download
mv: cannot stat ‘OpenCV-android-sdk’: No such file or directory
```

**Comment by iamareebjamal** [comment]
Another classic copy paste error https://github.com/yashk2000/phimpme-android/commit/fba853627e4a1bcc8ca691fed0e0b5b6f9596849#diff-4276627c10556d100f1c7e58fe053b68R4

You added /download, so it is saving the file as 'download', it was https://github.com/opencv/opencv/releases/download/2.4.13.3/opencv-2.4.13.3-android-sdk.zip before

You have to save it as opencv-3.2.0-android-sdk.zip

**Comment by yashk2000** [comment]
@iamareebjamal sorry sir. I did not see that.

**Comment by iamareebjamal** [comment]
Also, remove these lines:

```
sudo apt-get -qq update
sudo apt-get install -y unzip
sudo apt-get install -y unzip
```

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/phimpme-android/pull/2758#issuecomment-498760242

**Comment by yashk2000** [comment]
> [#2758 (comment)](https://github.com/fossasia/phimpme-android/pull/2758#issuecomment-498760242)

Sorry sir. I pasted the link from which I had downloaded openCV instead of the GitHub link.

**Comment by iamareebjamal** [comment]
BTW, open cv 3.2.0 was released in Dec 2016. Why are we using 2.5 years old version. Why not at least upgrade to the latest 3.x version. Or if possible 4.x? Since we are still doing a major upgrade 2.x to 3.x?

**Comment by iamareebjamal** [comment]
The 2.x version we were using was 1 year latest than 3.2.0. Let that sink in for a moment

**Comment by yashk2000** [comment]
@iamareebjamal sir I am trying to build to the app with 64-bit libraries right now. Once I am able to do this properly, I will send a proper pr with version 4.1.0.

**Comment by yashk2000** [comment]
@iamareebjamal sir, I updated OpenCV with version 4.0.1. It is working properly and building in the android studio. But still, there is the same type of error in travis. 
`Android NDK: ERROR:/home/travis/build/yashk2000/phimpme-android/app/src/main/jni/Android.mk:opencv_dnn: LOCAL_SRC_FILES points to a missing file    
  Android NDK: Check that /home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../staticlibs/armeabi-v7a/libopencv_dnn.a exists  or that its path is correct   
`

The folder `staticlibs` is not inside the `jni` folder. But still it is following that path which is causing the error. The file `libopencv_dnn.a` exists inside the `staticlibs` folder which is inside `app/src/main` but outside `jni`.

I will update the pull request tomorrow.

**Comment by iamareebjamal** [comment]
`/home/travis/build/yashk2000/phimpme-android/app/src/main/jni/../staticlibs/armeabi-v7a/libopencv_dnn.a` == `/home/travis/build/yashk2000/phimpme-android/app/src/main/staticlibs/armeabi-v7a/libopencv_dnn.a`

https://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/

**Comment by yashk2000** [comment]
@iamareebjamal thanks for the above resource. I am closing this pull request and opening a new one with OpenCV 4.0.1 and the build gradle version updated.

**Pull request closed without merging**
