### PR TITLE
Fixes #248:  The map shows no info in no internet state

### LINKED ISSUE #248: The map shows no info in no internet state
**Actual Behaviour**

The map fragment shows nothing on installation of app in no internet state. Happens with Xiaomi phones where the latest update makes a new installed application run without wifi on default.

**Expected Behaviour**

A dialog box should appear to direct the user to connect to internet in order to instantiate the map.

**Steps to reproduce it**

1. Install the application.
2. Switch off the wifi
3. Go to the Mapfragment tab.

**Screenshots of the issue**

screenshot_2017-03-28-03-08-48-155_vn mbm phimp me

screenshot_2017-03-28-02-55-55-529_vn mbm phimp me

**Would you like to work on the issue?**

Yes, I would like to work on it.

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes issue #248

Screenshots for the change: 

screenshot_2017-03-31-16-41-28-942_vn mbm phimp me

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
No, what if I click skip. The map won't load. Instead of the map we should display a no internet connection fragment and not a pop-up.

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @rohanagarwal94 we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/rohanagarwal94/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by rohanagarwal94** [comment]
@Abhi2424shek what if the user is not interested in the map altogether. Therefore he will skip the map in that case , and browse through other features of the app. Hence the dialog instead of the fragment.

**Comment by Abhi2424shek** [comment]
Can't we check for cache @rohanagarwal? I mentioned to show the internet bot available message instead of the map so that it would be a nice UI along with the bottom navigation bar so that he can go to other features of the app as well.

**Comment by rohanagarwal94** [comment]
"internet bot available message"  - @Abhi2424shek cant get you on this. Will you please elaborate or provide an example?

**Comment by Abhi2424shek** [comment]
Oh I am sorry I got a typo, it should be:
"internet not available".

**Comment by rohanagarwal94** [comment]
@Abhi2424shek the user should be able to view the map even when there is no internet. Since checking explicitly for map caching is not supported, an overlay fragment over the map is futile. @pa1pal views?

**Comment by pa1pal** [comment]
@rohanagarwal94 clear with the offline part. But it shows pop-up everytime I visit the maps while app is open. It seems annoying to me. What are your view?
Will snackbar be a good option for it, if we provide connect with internet action button on it.

**Comment by rohanagarwal94** [comment]
Even I feel snackbar will make more sense but the problem to that would be -
1. The snackbar will show everytime on the map when the internet is off, since user will not be able to skip it.
2. Not the regular flow of the app.

**Comment by pa1pal** [comment]
The first point is same in both the cases. But currently it requires one click extra to remove the dialog, because it blocks the UI thread. Although a short duration snackbar disappear on its own.

**Comment by Abhi2424shek** [comment]
I think we will need more opinions. I don't think snackbar would be a good solution.

**Comment by rohanagarwal94** [comment]
@pa1pal I think the disappearance feature kind of just fits in perfectly. Views before I start working on that?

**Comment by pa1pal** [comment]
@rohanagarwal94 go ahead.

**Comment by rohanagarwal94** [comment]
@pa1pal just realized it will interfere with the bottom nav bar. Any other solution?

**Comment by Abhi2424shek** [comment]
@rohanagarwal can I suggest something?
We will display an overdraw over the fragment stating that the internet connection is not available.

**Comment by rohanagarwal94** [comment]
@Abhi2424shek a dialog is an overlay itself. What specific difference are you trying to point out?

**Comment by Abhi2424shek** [comment]
Dialog interfere with the navigation, but not fragments.

**Comment by mariobehling** [comment]
Can we iterate on that and get to close this? Please make smaller PRs that can be merged within a shorter timeframe. Please resolve merge conflicts and resolve remaining items in follow up issues.

**Comment by mariobehling** [comment]
Closing it due to inactivity. Please open a new PR if you want to take this up again.

**Pull request closed without merging**
