### PR TITLE
Fixed #224 App is crashing in Tablets.

### LINKED ISSUE #224: App is crashing on tablets whenever using large,small,x-large layouts
**Actual Behaviour**

App is crashing in tablets because in other xmls like large,xtra large, small the proper views in not included. Null pointer exceptions.

**Expected Behaviour**

App should run properly in tablets.

screenshot_2017-03-22-16-14-08

**Steps to reproduce it**

Try to open app on tablets.

**LogCat for the issue**

FATAL EXCEPTION: main
                                                                 Process: vn.mbm.phimp.me, PID: 29825
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.mbm.phimp.me/vn.mbm.phimp.me.PhimpMe}: java.lang.NullPointerException
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2260)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5266)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.NullPointerException
                                                                     at vn.mbm.phimp.me.PhimpMe.onCreate(PhimpMe.java:579)
                                                                     at android.app.Activity.performCreate(Activity.java:5277)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2325) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:145) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:145) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5266) 
                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) 
                                                                     at dalvik.system.NativeStart.main(Native Method) 

**Would you like to work on the issue?**

Yes. Please let me know. I solved the errors and want to send PR.

### PR DESCRIPTION
**Pull request by mohitmanuja**
#224 

Changes: 
Removed separate layout for tablets, no need for them.
Checked in tablets: App is working perfectly.

Screenshots for the change: 
screenshot_2017-03-22-16-14-08

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @mohitmanuja we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/mohitmanuja/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mohitmanuja** [comment]
@phimpme-danger Please review it.

**Comment by Abhi2424shek** [comment]
It's a bot lol.

**Comment by mohitmanuja** [comment]
Hahahaha I am in doubt. @Abhi2424shek Thanks.

**Pull request merged**
