### PR TITLE
Added the Yellow Enhance Filter

### LINKED ISSUE #1907: Add a yellow enhancing color filter
**New Feature**
Add a filter that enhances the yellow colour on the image.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixed #1907 

Changes: Added the filter

Screenshots for the change: 
screenshot_20180228-144257
screenshot_20180228-144303

### CODE REVIEW

**Comment by batbrain7** [comment]
@abishekvashok @isuruAb please review!!

**Comment by isuruAb** [comment]
@batbrain7  please resolve conflicts

**Comment by batbrain7** [comment]
Surely following up on this @isuruAb

**Comment by batbrain7** [comment]
@isuruAb resolved the conflicts please review now!

**Comment by sauravvishal8797** [comment]
@batbrain7 Please resolve the conflicts.

**Pull request merged**
