### PR TITLE
Added the feature to edit images in landscape mode

### LINKED ISSUE #1615: Add Editing feature in Landscape mode
**Actual Behaviour**

Currently on rotating a device when we are editing a photo nothing happens.
**Expected Behaviour**

I want to make a feature that allows the app to edit even when in landscape mode.

**Steps to reproduce it**

Open any image from gallery, click on the edit button and then rotate the device.

**Would you like to work on the issue?**

Yes, definitely

### PR DESCRIPTION
**Pull request by batbrain7**
Fix #1615 

Changes: 
Added the feature to edit images even when in landscape mode.

Screenshots for the change: 
screenshot_20180108-172846
screenshot_20180108-172920
screenshot_20180109-155038

### CODE REVIEW

**Comment by batbrain7** [comment]
@isuruAb this is the PR corresponding to #1618 
I faced some errors on my side in that PR so I sent a new PR with the changes although the PR was already approved,
Please review and merge this PR

**Comment by abishekvashok** [comment]
Please check the failing build @batbrain7

**Comment by batbrain7** [comment]
@abishekvashok please review

**Comment by batbrain7** [comment]
@anantprsd5 @isuruAb @abishekvashok please merge this approved PR!!

**Comment by batbrain7** [comment]
@abishekvashok @anantprsd5 @isuruAb please merge this approved PR!!

**Pull request merged**
