### PR TITLE
refactor: Replaced deprecated managedQuery() with getContentResolver().query()

### PR DESCRIPTION
**Pull request by CloudyPadmal**

### CODE REVIEW

**Comment by pa1pal** [comment]
@CloudyPadmal Squash your commits in to one.

**Comment by heysadboy** [comment]
@pa1pal Hey, it would be great if we could update readme to tell all the coming contributors to send the pull request for development branch. I see last few are being made for master.

**Comment by pa1pal** [comment]
Yes it is necessary. I making necessary changes.

**Comment by heysadboy** [comment]
@pa1pal Thanks.

**Pull request closed without merging**
