### PR TITLE
Fixed #410 Info is not visible in dark theme.

### LINKED ISSUE #410: Image info is not visible in gallery fragment on dark theme.
**Actual Behaviour**
 
Right now image info in gallery fragment is not visible in the dark theme.

**Expected Behaviour**

Image info should be visible in galleryfragment on tap of info.

**Steps to reproduce it**

1. Select Dark theme.
2. Open any image and tap on fab info button.

**Screenshots of the issue**

screenshot_2017-05-06-23-51-52-216_vn mbm phimp me

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by mohitmanuja**
Fixes issue #410 

Changes: 
Now the info is visible in the dark theme.

Screenshots for the change: 
screenshot_2017-05-07-20-08-13-534_vn mbm phimp me

### CODE REVIEW

**Comment by phimpme-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">:tada: Thanks for the PR @mohitmanuja we hope you have changed the variables in the upload_apk_forks.sh its for easy moderation.</td>
    </tr>
  </tbody>
</table>

:link: Maintainers: the apk to test can be found at https://github.com/mohitmanuja/phimpme-android/blob/apk/app-debug.apk

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pa1pal** [comment]
yes I agree dark color info popup for dark theme.

**Comment by mohitmanuja** [comment]
@pa1pal  @vinaysajjanapu  
I have done the changes as you suggested.  

whatsapp image 2017-05-08 at 11 13 58 pm

**Comment by vinaysajjanapu** [comment]
I think those are not the proper dark theme colors. Blue should be replaced be colorPrimaryTheme and white by themeCardColor. Refer dark theme in styles

**Comment by mohitmanuja** [comment]
Okay @vinaysajjanapu Let me check, will update.

**Comment by mohitmanuja** [comment]
whatsapp image 2017-05-09 at 12 58 42 am
 
@vinaysajjanapu

**Comment by vinaysajjanapu** [comment]
Yeah it is fine.  But wouldn't it look better if the bg color is little lighter than header color of popup?
@pa1pal @mohitmanuja

**Comment by mohitmanuja** [comment]
screenshot_2017-05-09-22-02-04-244_vn mbm phimp me
@vinaysajjanapu  I tried ColorWindowBackgroundInverse(#303030) is it looking good now ?

**Comment by pa1pal** [comment]
Yes @mohitmanuja. 
Commit your changes.

**Pull request merged**
