### PR TITLE
Cleared all activity stack history on reset

### PR DESCRIPTION
**Pull request by mohitmanuja**
Fixes issue #530 
Changes:

On reset -
Cleared all activity stack history and re-opened the app.
It can be checked by the back press after reset.

### CODE REVIEW

**Comment by mohitmanuja** [comment]
@pa1pal Yes, Right now I am clearing all the stack history of activity and re-opening this app or we can call finish on setting only that will also work.
So should I finish settingActivity instead of clearing all stack?

**Comment by pa1pal** [comment]
@mohitmanuja Clearing stack is one option or some other way to prevent re opening the same activity again on top of it.

**Comment by mohitmanuja** [comment]
@pa1pal On click on reset settings in camera settings we have to close that activity right?

**Comment by pa1pal** [comment]
Yes

**Comment by mohitmanuja** [comment]
So simply we can call finish(); beacause it is in settingActivity at that time.

**Comment by pa1pal** [comment]
for that yes.

**Comment by mohitmanuja** [comment]
So that is what I am saying instead of clearing stack we can do finish() , I will update my PR and will call finish() on reset to finish the settingActivity.

**Comment by pa1pal** [comment]
@mohitmanuja yes for settings is fine. 
I confused in which context you asked. But add that part as well, which I commented. For not adding activity over the same activity.

**Comment by mohitmanuja** [comment]
That is the different issue #532 to handle the activity stack @pa1pal. and yes I will do as you are saying If(item.IsChecked()).

**Comment by mohitmanuja** [comment]
So I think on reset clearing all stack and the opening app is again fine? (Did in this PR)
or should I finish settingActivity only.

**Comment by pa1pal** [comment]
opening app again is fine.

**Comment by mohitmanuja** [comment]
Okay, that is done. Review this PR.

**Pull request merged**
