### PR TITLE
Material Design Theme Change, Settings Screen Re-Design

### PR DESCRIPTION
**Pull request by dynamitechetan**
Changes: 
- Added a Material Theme.
- Redesigned Settings Screen
- Added Bottom Bar Shadow
- CardView for showing Local Photos grid

Screenshots for the change: 
Screenshot1     &nbsp;  &nbsp;        Screenshot2

### CODE REVIEW

**Comment by haroonrashid235** [comment]
Looks good. Do we need cardViews in there?

**Comment by dynamitechetan** [comment]
@haroonrashid235 didn't understood?

**Comment by pa1pal** [comment]
@dynamitechetan Good work.
As you are changing the complete UI. So change the screenshots in the Readme in this PR only.

**Comment by dynamitechetan** [comment]
okay.

**Pull request merged**
