### PR TITLE
Fixed  #1719 the scrollbar color is changing according to primary color

### LINKED ISSUE #1719: After changing the PrimaryColor the scrollbar in albumsMode (not albumMode) doesn't change.
**Actual Behaviour**
when you change the primary color the scrollbar's color is changed every where except in albumsMode, that is, when there are albums in LFMainActivity.Only when you restart the app it is changed.

**Expected Behaviour**

The scrollbar's color should change according to primary color.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by raj10071997**
Fixed  #1719

Changes: Since there is no inbuilt method to change the color of scrollbar of recyclerView dynamically. So Made a CustomScrollBarRecyclerView class and overided the method to change the color.

### CODE REVIEW

**Comment by codedsun** [comment]
Kindly fix the Codacy fail-test !

**Comment by raj10071997** [comment]
@codedsun I have resolved the Codacy error. Please review this PR.

**Comment by abishekvashok** [comment]
It's taking infinity time

**Comment by raj10071997** [comment]
@abishekvashok  I don't understand your question?? Please elaborate the issue.

**Comment by abishekvashok** [comment]
Codeacy. Can you close and reopened this pr to restart tests pls?

**Comment by raj10071997** [comment]
Actually the error was - use explicit scoping rather than default package
private level. So I searched for this error ,it was because I didn't
declare my CustomScrollBarRecyclerView objects private. So when I tried to
declare them private the butter knife library showed error that the
bindView objects must not be declared private or static. So I manually
declared those objects private and bind the recycler views from
activity_leafpic.xml to these objects. You can search for the above error.
Codacy has already resolved this PR, so in my view there is no need to
reopen the PR. 😀

**Comment by anantprsd5** [comment]
Please resolve conflicts

**Comment by raj10071997** [comment]
@anantprsd5 @isuruAb All the conflicts have been resolved and travis build has also been passed.

**Pull request merged**
