### PR TITLE
chore: change play store icon

### LINKED ISSUE #2731: Adapt icon to new Google Playstore Requirements
Google has updated their playstore requirements. Please update the icon accordingly:

https://developer.android.com/google-play/resources/icon-design-specifications

When creating your artwork, ensure it conforms to the following:

- Final size: 512px x 512px
- Format: 32-bit PNG
- Color space: sRGB
- Max file size: 1024KB
- Shape: Full square – Google Play dynamically handles masking. Radius will be equivalent to 20% of icon size.
- Shadow: None – Google Play dynamically handles shadows. See 'Shadows' section below on including shadows within your artwork.

### PR DESCRIPTION
**Pull request by ranjsa**
Fixed #2731 

Changes: Updated the icon in  phimpme-android/app/src/main/ic_launcher-web.png

As first the icon was using the rounded mask but according to google guidelines shape of the icon should be full square and Google Play will dynamically handle masking . 

Reference : https://developer.android.com/google-play/resources/icon-design-specifications

Screenshots of the change: 

https://drive.google.com/file/d/1uvaEPvFM8BgarLJiCSBYk8JjK3ciCX6g/view?usp=sharing

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Too much padding

**Comment by yashk2000** [comment]
Don't we have to replace the app icons currently in the 'mipmap` folders too?

**Comment by iamareebjamal** [comment]
No

**Comment by yashk2000** [comment]
But those aren't showing up in showing up in changed files right now.

**Comment by iamareebjamal** [comment]
> Don't we have to replace the app icons currently in the 'mipmap` folders too?

No

**Comment by yashk2000** [comment]
Ohk.

**Comment by iamareebjamal** [comment]
Now it's too less. Please use the gridline given by Google

**Comment by ranjsa** [comment]
ok .......

**Comment by ranjsa** [comment]
@iamareebjamal  modified the icon according to google guidelines

**Comment by yashk2000** [comment]
Looks better now. Can you please squash the commits?

**Comment by iamareebjamal** [comment]
Please change this file and revert the ic_web.png

https://github.com/fossasia/phimpme-android/blob/development/fastlane/metadata/android/en-US/images/icon.png

**Comment by ranjsa** [comment]
OK sure .....

**Comment by ranjsa** [comment]
@iamareebjamal  files changed and commits squashed

**Comment by iamareebjamal** [comment]
Resolve conflicts

**Comment by iamareebjamal** [comment]
Irrelevant changes and 32 file changes

**Comment by ranjsa** [comment]
@iamareebjamal  I don't know where i went wrong . Can you please suggest me what should i do to resolve this conflicts .

**Comment by ranjsa** [comment]
I reverted back to previous commit .... Is it good now

**Pull request merged**
