### PR TITLE
Replaced old icons with Material Design ones and enhanced overall design

### PR DESCRIPTION
**Pull request by oanarosca**
In this (rather huge, sorry) PR, I:

- replaced the icons in the `take photo`/`camera` activity and `crop image` with Material Design, in hdpi, mdpi, xdpi, xxdpi and xxxdpi sizes
- fixed a bug with switching the flash when taking a picture
- enhanced the `add wordpress account` activity
- fixed a bug that caused the view element in `crop image` to overflow
This fixes issue #26.
Here is one preview of the new design:
whatsapp image 2017-01-06 at 09 27 49

### CODE REVIEW

**Comment by pa1pal** [comment]
@oanarosca Nice effort :+1: 
As per the task description, you first open a issue for the design improvements you are planning. No problem you can open it now and refer to this PR.

**Comment by oanarosca** [comment]
@pa1pal Done!

**Comment by pa1pal** [comment]
@oanarosca What is the source/ License of the images you used?

**Comment by oanarosca** [comment]
I used icons from the [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/), which are licensed under Creative Commons Attribution 3.0.

**Comment by pa1pal** [comment]
@oanarosca Great. Good effort. Keep it up.

**Pull request merged**
