### PR TITLE
FIXED#2244 Changed the vector drawable

### LINKED ISSUE #2244: Snapchat icon barely visible in sharing activity in Light theme(default)
**Actual Behaviour**
The Snapchat icon is too thin outlined and is barely visible in sharing activity in Light theme(default theme)

**Expected Behaviour**
It should be clearly visible whatever the background is

**Steps to reproduce it**
1) Open the app select an image and press share
2) Sharing activity opens 
3) Snapchat icon is barely visible

**Screenshots of the issue**

a318af72-1fac-40fb-a15c-6e4f27b556a0

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by codepoet2017390**
Fixed #2244 

Changes: Changed the vector drawable so that it is clearly visible now

**Screenshots of the change:**
 
a375ea60-3988-4dd2-98a6-c1da90dc12b0

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@codepoet2017390 Still it is not as clear as the other items(both icon and text), maybe you can change the color to a bit darker shade of yellow.

**Comment by codepoet2017390** [comment]
@sauravvishal8797  Ya surei did not change it because it was the signature color of Snapchat

**Comment by abishekvashok** [comment]
It would be better if you could use cards.

**Comment by codepoet2017390** [comment]
@abishekvashok  sure

**Pull request closed without merging**
