### PR TITLE
Fix for issue#2483: Replaced harcoded dimensions with dimens resource values.

### LINKED ISSUE #2483: Hardcoded dimension values in xml files.
**Actual Behaviour**

Dimension values are hardcoded in xml files in many places.

**Expected Behaviour**

Hardcoded dimension values should be replaced with dimens resource values.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2483 
Changes: Replaced all hardcoded dimensions values with dimens resource values.

### CODE REVIEW

**Comment by abishekvashok** [comment]
Looks really cool 👌

**Comment by sauravvishal8797** [comment]
@yashk2000 Please resolve the conflicts.

**Comment by yashk2000** [comment]
@sauravvishal8797 I have resolved the conflicts. Please review.

**Comment by yashk2000** [comment]
@abishekvashok @sauravvishal8797 please review, I have resolved the conflicts.

**Pull request merged**
