### PR TITLE
enablesmallscreen

### PR DESCRIPTION
**Pull request by SunitRoy2703**
This pullrequest enables the Account Activity for small screen devices, In previous version bottom navigation was overlapping the recyclerView

### CODE REVIEW

**Comment by SunitRoy2703** [comment]
IMG-20201002-WA0022 1

this a screenshot of a small device

**Comment by Raunaksingh100** [comment]
@SunitRoy2703 plz mentioned the issue number in the pr description

**Comment by SunitRoy2703** [comment]
> @SunitRoy2703 plz mentioned the issue number in the pr description

https://github.com/fossasia/phimpme-android/issues/3051 

i think it's #3051 
@Raunaksingh100

**Comment by mariobehling** [comment]
New PRs should pass the integration test. Please check how you could make this pass. Thank you

**Review by riturajjain2000 — APPROVED** [review]
Looks Good to me

**Comment by SunitRoy2703** [comment]
> Looks Good to me

can tell me how to pass
 "continuous-integration/travis-ci Expected — Waiting for status to be reported"

**Comment by riturajjain2000** [comment]
Please read 

> > Looks Good to me
> 
> can tell me how to pass
> "continuous-integration/travis-ci Expected — Waiting for status to be reported"

Read #10204

**Comment by riturajjain2000** [comment]
> 
> can tell me how to pass
> "continuous-integration/travis-ci Expected — Waiting for status to be reported"

Read https://github.com/travis-ci/travis-ci/issues/10261

**Pull request closed without merging**
