### PR TITLE
Landing page for Phimpme built on jekyll

### LINKED ISSUE #683: Phimp.me app landing page
**Actual Behaviour**

There is no landing page for phimpme app

**Expected Behaviour**

Landing page for URL: [phimp.me](phimp.me)

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by pa1pal**
Fix #683 

Changes: 

- [x] Created gh-pages orphan branch in main repository
- [x] added jekyll open source theme for landing page
- [x] tested on forked repo

Demo: [https://pa1pal.github.io/phimpme-android/](https://pa1pal.github.io/phimpme-android/)

### CODE REVIEW

**Comment by pa1pal** [comment]
@mariobehling please see demo here  [https://pa1pal.github.io/phimpme-android/](https://pa1pal.github.io/phimpme-android/)

**Comment by Subhankar29** [comment]
The phone screenshot has two navigation bar. 
screen shot 2017-06-29 at 11 57 34 pm
Please look into it.

**Comment by pa1pal** [comment]
@Subhankar29  Yes there is some modification required in the css. Will do.

**Comment by the-dagger** [comment]
We could probably use  a better screenshot @pa1pal?

**Comment by the-dagger** [comment]
@pa1pal maybe you could try this template? 
https://github.com/FaizMalkani/appsite

Looks pretty good to me.

**Comment by pa1pal** [comment]
@Subhankar29 fixed the size issue in `scss` 
@the-dagger Screenshot changed. And the landing page you suggested looks great. Will move to this appsite.
Thanks for switching the gh-pages in Phimpme settings. So lets first merge this to show correct changes in current landing page : [http://fossasia.github.io/phimpme-android/](http://fossasia.github.io/phimpme-android/) for now.

**Pull request merged**
