### PR TITLE
Fix#1275 -Image Details UI Updated

### LINKED ISSUE #1275: UI Update for Description of Image.
**Actual Behaviour**

A dialog box appears for the info /details of image

**Expected Behaviour**
The UI should be updated.

**Screenshots For Updated UI**

The description should look something like this.
image

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by codedsun**
Fix #1275 - UI Updated

Changes: Added a layout for the whole.

Screenshots for the change: 
screenshot_20171008-021304

@anantprsd5 Kindly review.

### CODE REVIEW

**Comment by codedsun** [comment]
@mohitmanuja kindly review!

**Comment by codedsun** [comment]
@mohitmanuja  chck this!

**Comment by mohitmanuja** [comment]
@codesun please post image in each theme and keep the text size small.

**Comment by codedsun** [comment]
@mohitmanuja ok!  what shall be the text size?

**Comment by mohitmanuja** [comment]
Try to reduce 2 sp in both.

**Comment by codedsun** [comment]
@mohitmanuja Done the changes.!

**Comment by codedsun** [comment]
@aditya98ak @sridharjajoo Review plz !

**Comment by mohitmanuja** [comment]
@anantprsd5 please check this if it is better then the previous one then merge it.

**Comment by codedsun** [comment]
@anantprsd5 What is the issue with codacy?

**Pull request merged**
