### PR TITLE
changed the layout account manager using swithes for sign in

### LINKED ISSUE #665: Change Account manager layout used sign in on Activity on Switch action
**Actual Behaviour**

Currently, Sign in work perform on dialog fragment, and it later updated the recyclerview of account manager. There is a problem with the instance of the Callbackmanager in it. We are changing the layout of using more effective approach, using Switches, for sign In.
Sign In mean Switch On and Signed out means Switch off

**Expected Behaviour**

Change in the layout of account manager
image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by pa1pal**
Fix #665 

Changes: 
- [x] Added switch to sign in
- [x] CardView layout
- [x] set things in recyclerview.

#### Screenshot
account_manager_new

### CODE REVIEW

**Comment by pa1pal** [comment]
@mohitmanuja @anantprsd5  @Subhankar29 @vinaysajjanapu  Please review.

**Comment by pa1pal** [comment]
@mohitmanuja @anantprsd5 @Subhankar29 @vinaysajjanapu Please review.

**Comment by anantprsd5** [comment]
'''
FATAL EXCEPTION: main
                                                                      Process: org.fossasia.phimpme, PID: 28180
                                                                      android.content.ActivityNotFoundException: Unable to find explicit activity class {org.fossasia.phimpme/org.fossasia.phimpme.accounts.AccountActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                          at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
                                                                          at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3990)
                                                                          at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                          at android.app.Activity.startActivityForResult(Activity.java:3951)
                                                                          at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                          at android.app.Activity.startActivity(Activity.java:4274)
                                                                          at android.app.Activity.startActivity(Activity.java:4242)
                                                                          at org.fossasia.phimpme.base.BaseActivity.onNavigationItemSelected(BaseActivity.java:53)
                                                                          at android.support.design.widget.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:184)
                                                                          at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                          at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                                          at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                                          at android.support.design.internal.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:90)
                                                                          at android.view.View.performClick(View.java:5226)
                                                                          at android.view.View$PerformClick.run(View.java:21350)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5582)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main
'''

**Comment by anantprsd5** [comment]
@pa1pal App crashes on opening the accounts activity

**Comment by pa1pal** [comment]
@anantprsd5  fixed now. Thanks.

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Pull request merged**
