### PR TITLE
chore: Removed obsolete configurations and updated versions of dependencies.

### LINKED ISSUE #2763: Change compile to implementation and update dependencies.
**Describe the chore**
Compile has been deprecated and should be changed to implementation. Some dependencies also need to be updated.

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2763 

Changes: Changes `compile` to `implementation`, `debugCompile` to `debugImplementation` and other related changes. Also, updated versions of dependencies used.

### CODE REVIEW

**Comment by mariobehling** [comment]
Travis is failing. Please fix.

**Comment by yashk2000** [comment]
Yes sir. I am working on fixing it.

**Comment by yashk2000** [comment]
@iamareebjamal @abishekvashok I am not able to resolve this error:

`Dependencies using groupId com.android.support and androidx.* can not be combined but found IdeMavenCoordinates{myGroupId='com.android.support', myArtifactId='recyclerview-v7', myVersion='28.0.0', myPacking='aar', myClassifier='null'} and IdeMavenCoordinates{myGroupId='androidx.drawerlayout', myArtifactId='drawerlayout', myVersion='1.0.0', myPacking='aar', myClassifier='null'} incompatible dependencies less... (Ctrl+F1) 
Inspection info:There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).` 

`Issue id: GradleCompatible`


Could you please help with this? As far as I know, we are not using android.x in the app yet.

**Comment by iamareebjamal** [comment]
You are using androidx somewhere in some transitive dependency

**Comment by yashk2000** [comment]
@iamareebjamal how do I find the dependency in which androidx has been used?

**Comment by iamareebjamal** [comment]
./gradlew app:dependencies

**Comment by yashk2000** [comment]
@iamareebjamal did that. I was still unable to find androidx anywhere.

**Comment by iamareebjamal** [comment]
That's impossible.

**Comment by yashk2000** [comment]
@iamareebjamal apologies. I found out that androidx is being used. I went through all the dependencies manually this time. Earlier I was using the search feature of the terminal itself, which may be cause me to skip androidx.

**Comment by yashk2000** [comment]
@iamareebjamal how do I fix this: `error: package android.test does not exist`

ApplicationTestCase was deprecated in API Level 24.

**Comment by iamareebjamal** [comment]
Update the tests

**Comment by yashk2000** [comment]
@iamareebjamal how do I replace the ApplicationTestCase?

**Comment by yashk2000** [comment]
@iamareebjamal @mariobehling @abishekvashok @adityastic please review.

**Pull request merged**
