### PR TITLE
Fix for issue#2385: An alert is shown if invalid time limits are entered.

### LINKED ISSUE #2385: Issue when entering slideshow duration.
**Actual Behaviour**

If slideshow duration is entered less than 2 seconds or greater than 10s, the dialog closes and a toast is shown.

**Expected Behaviour**

If the dialog closes, the user has to open the menu and press slideshow again to enter time. Instead of closing the dialog on invalid time, an alert should be shown to the user about the time limit and dialog for entering the time should stay on.

**Steps to reproduce it**

1) Open an album.
2) Click on menu and start slideshow.
3) Enter time greater than 10 seconds. The dialog closes and a toast is shown.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixed #2385 

Changes: Now an alert is shown if invalid time limits are entered while starting a slideshow.

Screenshots of the change: 
screencap
screencap1

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@yashk2000 I think you can disable the Ok button here when the invalid time limits are entered.

**Comment by yashk2000** [comment]
@sauravvishal8797 if user inputs invalid time, how will the user be made aware of the correct range of time?

**Comment by sauravvishal8797** [comment]
@yashk2000 According to the second ss, an alert is displayed right? with the correct max limit. I'm just saying you can disable the Ok button when the user enters invalid limit so that the user either has to enter the valid limit in order for the Ok button to work, or can abort by clicking on the cancel button.

**Comment by yashk2000** [comment]
@sauravvishal8797 Ok. I'll make the changes

**Comment by sauravvishal8797** [comment]
@yashk2000 please resolve the conflicts.

**Comment by yashk2000** [comment]
Resolved the conflicts @sauravvishal8797

**Comment by yashk2000** [comment]
@abishekvashok the user need not press the button to see the error. If the user enters a value less than 2 seconds or greater than 10 seconds, the alert automatically pops up.

ezgif com-video-to-gif 10

**Comment by abishekvashok** [comment]
> @abishekvashok the user need not press the button to see the error. If the user enters a value less than 2 seconds or greater than 10 seconds, the alert automatically pops up.

I mentioned about the red icon on the textView. Please change it and add textView as suggested.

**Comment by yashk2000** [comment]
> > @abishekvashok the user need not press the button to see the error. If the user enters a value less than 2 seconds or greater than 10 seconds, the alert automatically pops up.
> 
> I mentioned about the red icon on the textView. Please change it and add textView as suggested.

@abishekvashok made the changes. Please review.

**Pull request merged**
