### PR TITLE
Correcting grammatical errors in README.md

### LINKED ISSUE #1962: Grammatical errors in README.md
**Actual Behaviour**

There are some grammatical errors in README.md

**Expected Behaviour**

README.md should be error-free.

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

### PR DESCRIPTION
**Pull request by DhruvamSharma**
Fixed #1962 

Changes: Removed grammatical errors from README.md

### CODE REVIEW

**Comment by DhruvamSharma** [comment]
I did not add those spaces. Should I remove them and add tabs again?

**Comment by kurianbenoy** [comment]
@DhruvamSharma  I would suggest you to change the word **favourite** back and and then edit the PR.
Rest is fine

**Comment by DhruvamSharma** [comment]
Okay. I'll change the PR

**Comment by DhruvamSharma** [comment]
@kurianbenoy  Done sir! Sorry for late changes.

**Comment by kurianbenoy** [comment]
Good work @DhruvamSharma  .Keep on contribution to the project

**Comment by DhruvamSharma** [comment]
Thank you sir!!

**Pull request merged**
